---

power_sequencer:
  # Enable PSU when Chassis is on or PCH is still powered
  - BCM1_Unit:
      in:
        or:
          - name: "STATE_REQ_CHASSIS_ON"
          - name: "PCH_VR_Off"
            invert: true
      out:
        name: "bcm1_On"

  - BCM2_Unit:
      in:
        or:
          - name: "STATE_REQ_CHASSIS_ON"
          - name: "PCH_VR_Off"
            invert: true
      out:
        name: "bcm2_On"

  - BCM3_Unit:
      in:
        or:
          - name: "STATE_REQ_CHASSIS_ON"
          - name: "PCH_VR_Off"
            invert: true
      out:
        name: "bcm3_On"

  - M2_SSD1_Unit:
      in:
        and:
          - name: "SYS_PWROK"
        or:
          - name: "PLUG_DETECT_M2_SSD_CARRIER1"
          - name: "PLUG_DETECT_M2_SSD1"
      out:
        name: "p3v3_m2_ssd1_On"
      delay_usec: 100000

  - M2_SSD2_Unit:
      in:
        and:
          - name: "SYS_PWROK"
        or:
          - name: "PLUG_DETECT_M2_SSD_CARRIER2"
          - name: "PLUG_DETECT_M2_SSD2"
      out:
        name: "p3v3_m2_ssd2_On"
      delay_usec: 100000

  - M2_RST_M2_SSD1_PERST_Unit:
      in:
        or:
          - name: "FM_SLPS3"
          - name: "RSMRST"
          - name: "p3v3_m2_ssd1_PowerGood"
            input_stable_usec: 100000  # PCIe spec: 100msec
            invert: true
          - name: "p3v3_m2_ssd1_PowerGood"
            invert: true
          - name: "PLTRST"
      out:
        name: "RST_M2_SSD1_PERST"

  - M2_RST_M2_SSD2_PERST_Unit:
      in:
        or:
          - name: "FM_SLPS3"
          - name: "RSMRST"
          - name: "p3v3_m2_ssd2_PowerGood"
            input_stable_usec: 100000  # PCIe spec: 100msec
            invert: true
          - name: "p3v3_m2_ssd2_PowerGood"
            invert: true
          - name: "PLTRST"
      out:
        name: "RST_M2_SSD2_PERST"

  - LED_PWR_DWR:
      in:
        and:
          - name: "ACPI_STATE_IS_S0"
          - name: "FM_NIC1_RST"
            invert: true
          - name: "FM_NIC2_RST"
            invert: true
      out:
        name: "LED_PWR_DWR"

  # Clock is required for early DbC
  - FM_CK440Q_DEV_Enable:
      in:
        or:
          - name: "STATE_REQ_CHASSIS_ON"
          - name: "RSMRST"
            invert: true
            input_stable_usec: 10000
          - name: "RSMRST"
            invert: true
      out:
        name: "FM_CK440Q_DEV_EN"

  # For early platform bringup turn it on early
  - FM_DB2000_DEV_Enable:
      in:
        and:
          - name: "FM_CK440Q_DEV_EN"
      out:
        name: "FM_DB2000_DEV_EN"

  - SSD1_LED_Unit:
      in:
        and:
          - name: "p3v3_m2_ssd1_PowerGood"
            input_stable_usec: 100000
          - name: "p3v3_m2_ssd1_PowerGood"
      out:
        name: "LED_SSD1"

  - SSD2_LED_Unit:
      in:
        and:
          - name: "p3v3_m2_ssd2_PowerGood"
            input_stable_usec: 100000
          - name: "p3v3_m2_ssd2_PowerGood"
      out:
        name: "LED_SSD2"

regulators:
  - name: "bcm1"
    allow_missing: true
  - name: "bcm2"
    allow_missing: true
  - name: "bcm3"
    allow_missing: true
  - name: "p3v3_m2_ssd1"
    allow_missing: true
    allow_faulting: true
  - name: "p3v3_m2_ssd2"
    allow_missing: true
    allow_faulting: true

floating_signals:
  - "bcm1_PowerGood"
  - "bcm1_Enabled"
  - "bcm1_Fault"
  - "bcm2_PowerGood"
  - "bcm2_Enabled"
  - "bcm2_Fault"
  - "bcm3_PowerGood"
  - "bcm3_Enabled"
  - "bcm3_Fault"
  - "p3v3_m2_ssd1_Enabled"
  - "p3v3_m2_ssd2_Enabled"
  - "p3v3_m2_ssd1_Fault"
  - "p3v3_m2_ssd2_Fault"

inputs:
  - name: "PLUG_DETECT_M2_SSD_CARRIER1"
    type: "gpio"
    signal_name: "PLUG_DETECT_M2_SSD_CARRIER1"
    active_low: true
    pullup: true
  - name: "PLUG_DETECT_M2_SSD_CARRIER2"
    type: "gpio"
    signal_name: "PLUG_DETECT_M2_SSD_CARRIER2"
    active_low: true
    pullup: true
  - name: "PLUG_DETECT_M2_SSD1"
    type: "gpio"
    signal_name: "PLUG_DETECT_M2_SSD1"
    active_low: true
    pullup: true
  - name: "PLUG_DETECT_M2_SSD2"
    type: "gpio"
    signal_name: "PLUG_DETECT_M2_SSD2"
    active_low: true
    pullup: true

outputs:
  - name: "RST_M2_SSD1_PERST_N"
    type: "gpio"
    signal_name: "RST_M2_SSD1_PERST"
    active_low: true
    description: "M.2 reset line"
  - name: "RST_M2_SSD2_PERST_N"
    type: "gpio"
    signal_name: "RST_M2_SSD2_PERST"
    active_low: true
    description: "M.2 reset line"
  - name: "led_pwr_dwr"
    type: "led"
    signal_name: "LED_PWR_DWR"
  - name: "FM_CK440Q_DEV_EN"
    type: "gpio"
    signal_name: "FM_CK440Q_DEV_EN"
  - name: "FM_DB2000_DEV_EN"
    type: "gpio"
    signal_name: "FM_DB2000_DEV_EN"
  - name: "led_m2_ssb_ssd1_power"
    type: "led"
    signal_name: "LED_SSD1"
  - name: "led_m2_ssb_ssd2_power"
    type: "led"
    signal_name: "LED_SSD2"
