---

# Contains logic to power sequence an Intel Xeon CPU.

inputs:
  # FIVR_FAULT is not read as THERMTRIP_N is driven as well.
  - name: "H_LVT3_CPU2_THERMTRIP_OUT_N"
    signal_name: "H_LVT3_CPU2_THERMTRIP"
    type: "gpio"
    active_low: true
    pullup: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.
    gate_input: true
    gated_idle_high: true

  - name: "system/chassis/motherboard/cpu2"
    type: "dbus_presence"
    pullup: true
    signal_name: "FM_CPU2_SKTOCC"
    description: "CPU2 socket is occupied."

  - name: "PWRGD_CHA_CPU2"
    signal_name: "PWRGD_CHA_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel A power good."

  - name: "PWRGD_CHB_CPU2"
    signal_name: "PWRGD_CHB_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel B power good."

  - name: "PWRGD_CHC_CPU2"
    signal_name: "PWRGD_CHC_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel C power good."

  - name: "PWRGD_CHD_CPU2"
    signal_name: "PWRGD_CHD_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel D power good."

  - name: "PWRGD_CHE_CPU2"
    signal_name: "PWRGD_CHE_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel E power good."

  - name: "PWRGD_CHF_CPU2"
    signal_name: "PWRGD_CHF_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel F power good."

  - name: "PWRGD_CHG_CPU2"
    signal_name: "PWRGD_CHG_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel G power good."

  - name: "PWRGD_CHH_CPU2"
    signal_name: "PWRGD_CHH_CPU2"
    type: "gpio"
    pullup: true
    description: "CPU2 DDR Channel H power good."

  - name: "FM_CPU2_PKG_ID0"
    signal_name: "FM_CPU2_PKG_ID0"
    type: "gpio"
    pullup: true
    description: "CPU 0 PKGID"

  - name: "FM_CPU2_PKG_ID1"
    signal_name: "FM_CPU2_PKG_ID1"
    type: "gpio"
    pullup: true
    description: "CPU 0 PKGID"


outputs:
  - name: "H_LVT3_CPU2_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_PROCHOT"
    active_low: true
    pullup: true
    description: "CPU2 is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU2_AB_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_AB_DRAM_G"
    pullup: true
    description: "CPU2 memory channel AB power good."

  - name: "PWRGD_LVC3_CPU2_CD_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_CD_DRAM_G"
    pullup: true
    description: "CPU2 memory channel CD power good."

  - name: "PWRGD_LVC3_CPU2_EF_DRAM_G"
    type: "gpio"
    pullup: true
    signal_name: "PWRGD_LVC3_CPU2_EF_DRAM_G"
    description: "CPU2 memory channel EF power good."

  - name: "PWRGD_LVC3_CPU2_GH_DRAM_G"
    type: "gpio"
    pullup: true
    signal_name: "PWRGD_LVC3_CPU2_GH_DRAM_G"
    description: "CPU2 memory channel GH power good."

  - name: "RST_LVC3_CPU2_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU2_RESET"
    active_low: true
    pullup: true
    description: "CPU2 RESET_N"

  - name: "PWRGD_LVC3_CPU2_PWRGOOD"
    type: "gpio"
    pullup: true
    signal_name: "PWRGD_LVC3_CPU2_PWRGOOD"
    description: "Tell CPU2 power good."

  - name: "PWRGD_PLT_AUX_CPU2_LVT3"
    type: "gpio"
    signal_name: "PWRGD_PLT_AUX_CPU2"

  - name: "SEL_SMB_DIMM_CPU2"
    type: "gpio"
    active_low: true
    signal_name: "SEL_SMB_DIMM_CPU2"

  - name: "H_LVT3_CPU2_NMI"
    type: "gpio"
    pullup: true
    signal_name: "CPU2_NMI"

  - name: "FM_CPU2_DISABLE_COD_N"
    type: "gpio"
    pullup: true
    active_low: true
    signal_name: "FM_CPU2_DISABLE_COD"

  - name: "CATERR_CPU2_EN"
    type: "gpio"
    signal_name: "CATERR_CPU2_EN"

immutables:
  - signal_name: "H_LVT3_CPU2_PROCHOT"
    value: false
  - signal_name: "CPU2_NMI"
    value: false
  - signal_name: "FM_CPU2_DISABLE_COD"
    value: false
  - signal_name: "CATERR_CPU2_EN"
    value: true

power_sequencer:
  - PWRGD_LVC3_CPU2_AB_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHA_CPU2"
          - name: "PWRGD_CHB_CPU2"
          - name: "pvccd_hv_cpu2_PowerGood"
          - name: "DDR_POWER"
            input_stable_usec: 10000
      out:
        name: "PWRGD_LVC3_CPU2_AB_DRAM_G"

  - PWRGD_LVC3_CPU2_CD_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHC_CPU2"
          - name: "PWRGD_CHD_CPU2"
          - name: "pvccd_hv_cpu2_PowerGood"
          - name: "DDR_POWER"
            input_stable_usec: 10000
      out:
        name: "PWRGD_LVC3_CPU2_CD_DRAM_G"
  
  - PWRGD_LVC3_CPU2_EF_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHE_CPU2"
          - name: "PWRGD_CHF_CPU2"
          - name: "pvccd_hv_cpu2_PowerGood"
          - name: "DDR_POWER"
            input_stable_usec: 10000
      out:
        name: "PWRGD_LVC3_CPU2_EF_DRAM_G"

  - PWRGD_LVC3_CPU2_GH_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHG_CPU2"
          - name: "PWRGD_CHH_CPU2"
          - name: "pvccd_hv_cpu2_PowerGood"
          - name: "DDR_POWER"
            input_stable_usec: 10000
      out:
        name: "PWRGD_LVC3_CPU2_GH_DRAM_G"
  # DDR & CPU VRs

  # PVCCD_HV must be equal or higher than Vdd at all times.
  - PVCCD_HV_CPU2_Unit:
      in:
        or:
          - name: "pvccfa_ehv_cpu2_Enabled"
          - name: "pvccfa_ehv_fivra_cpu2_Enabled"
          - name: "pvccinfaon_cpu2_Enabled"
        and:
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "DDR_POWER"
        and_then_or: true
      out:
        name: "pvccd_hv_cpu2_On"

  - CPU2_DDR_PWRGD_Unit:
      in:
        and:
          - name: "pvccd_hv_cpu2_PowerGood"
      out:
        name: "CPU2_DDR_PWRGD"

  - SEL_SMB_DIMM_CPU2_Unit:
      in:
        or:
          - name: "CPU_POWER"
          - name: "CPU2_DDR_PWRGD"
            input_stable_usec: 10000
        and:
          - name: "FM_CPU2_SKTOCC"
        and_then_or: false
      out:
        name: "SEL_SMB_DIMM_CPU2"

  - PVCCFA_EHV_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvccd_hv_cpu2_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvccfa_ehv_fivra_cpu2_Enabled"
          - name: "pvccfa_ehv_fivra_cpu2_PowerGood"
            input_stable_usec: 1000
        and_then_or: true
      out:
        name: "pvccfa_ehv_cpu2_On"
  
  - PVCCFA_EHV_FIVRA_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvccd_hv_cpu2_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvccinfaon_cpu2_Enabled"
          - name: "pvccinfaon_cpu2_PowerGood"
            input_stable_usec: 1000
        and_then_or: true
      out:
        name: "pvccfa_ehv_fivra_cpu2_On"

  - PVCCINFAON_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvccfa_ehv_fivra_cpu2_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvnn_main_cpu2_Enabled"
          - name: "pvnn_main_cpu2_PowerGood"
            input_stable_usec: 10000
        and_then_or: true
      out:
        name: "pvccinfaon_cpu2_On"

  - PVNN_MAIN_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvccinfaon_cpu2_PowerGood"
            input_stable_usec: 2
        or:
          - name: "pvccin_cpu2_Enabled"
          - name: "pvccin_cpu2_PowerGood"
            input_stable_usec: 100
        and_then_or: true
      out:
        name: "pvnn_main_cpu2_On"
  
  - PVCCIN_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvnn_main_cpu2_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvpp_hbm_cpu2_Enabled"
          - name: "pvpp_hbm_cpu2_PowerGood"
            input_stable_usec: 1000
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            input_stable_usec: 20
        and_then_or: true
      out:
        name: "pvccin_cpu2_On"

  - PVPP_HBM_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_HBM_PRESENT"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvccin_cpu2_PowerGood"
            input_stable_usec: 2
          - name: "PWRGD_CPUPWRGD"
      out:
        name: "pvpp_hbm_cpu2_On"

  - CPU2_HBM_PRESENT_Unit:
      in:
        and:
          - name: "FM_CPU2_PKG_ID0"
            invert: true
          - name: "FM_CPU2_PKG_ID1"
      out:
        name: "CPU2_HBM_PRESENT"

  - CPU2_HBM_Gated_PowerGood_Unit:
      in:
        or:
          - name: "pvpp_hbm_cpu2_PowerGood"
          - name: "CPU2_HBM_PRESENT"
            invert: true
      out:
        name: "CPU2_HBM_Gated_PowerGood"

  - PWRGD_PLT_AUX_CPU2_Unit:
      in:
        and:
          - name: "CPU2_VR_Fault"
            invert: true
          - name: "FM_CPU2_SKTOCC"
        or:
          - name: "CPU2_SYS_PWROK" # Release after SYS_PWROK
            input_stable_usec: 100
          - name: "pvnn_main_cpu2_PowerGood"
            input_stable_usec: 1
        and_then_or: false
      out:
        name: "PWRGD_PLT_AUX_CPU2"

  # All VRs except optional HBM
  - CPU2_VR_PWRGD_Unit:
      in:
        and:
          - name: "pvccfa_ehv_cpu2_PowerGood"
          - name: "pvccfa_ehv_fivra_cpu2_PowerGood"
          - name: "pvccinfaon_cpu2_PowerGood"
          - name: "pvnn_main_cpu2_PowerGood"
          - name: "pvccin_cpu2_PowerGood"
      out:
        name: "CPU2_VR_PWRGD"

  # Power good & fault handling

  - PWRGD_LVC3_CPU2_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU2_DDR_PWRGD"
            # PDG: 2usec max from VR failure to SYS_PWROK low
          - name: "CPU2_VR_PWRGD" # fast path for emergency shutdown
          - name: "pvccin_cpu2_PowerGood"
            input_stable_usec: 1800
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_DB2000_DEV_EN" # Clock buffer enable
            input_stable_usec: 2000 # wait for clocks to be stable
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_HBM_Gated_PowerGood"
      out:
        name: "PWRGD_LVC3_CPU2_PWRGOOD"

  # All VRs except HBM
  - CPU2_SYS_PWROK_Unit:
      in:
        and:
          - name: "CPU2_VR_PWRGD"
          - name: "CPU2_DDR_PWRGD"
        or:
          - name: "FM_CPU2_SKTOCC"
            invert: true
        and_then_or: true
      out:
        name: "CPU2_SYS_PWROK"
  
  - CPU2_VR_Off_Unit:
      in:
        or:
          - name: "pvccfa_ehv_cpu2_Enabled"
          - name: "pvccfa_ehv_fivra_cpu2_Enabled"
          - name: "pvccinfaon_cpu2_Enabled"
          - name: "pvnn_main_cpu2_Enabled"
          - name: "pvccin_cpu2_Enabled"
          - name: "pvpp_hbm_cpu2_Enabled"
      out:
        name: "CPU2_VR_Off"
        active_low: true

  - CPU2_DDR_Off_Unit:
      in:
        or:
          - name: "pvccd_hv_cpu2_Enabled"
      out:
        name: "CPU2_DDR_Off"
        active_low: true
  
  - CPU2_VR_Off_Unit:
      in:
        and:
          - name: "CPU2_DDR_Off"
          - name: "CPU2_VR_Off"
      out:
        name: "CPU2_Off"
    
  - CPU2_VR_Fault_Unit:
      in:
        or:
          - name: "pvccfa_ehv_cpu2_Fault"
          - name: "pvccfa_ehv_fivra_cpu2_Fault"
          - name: "pvccinfaon_cpu2_Fault"
          - name: "pvnn_main_cpu2_Fault"
          - name: "pvccin_cpu2_Fault"
          - name: "pvpp_hbm_cpu2_Fault"
          - name: "pvccd_hv_cpu2_Fault"
          - name: "CPU2_THERMTRIP"
        and:
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "CPU2_VR_Fault"

  - CPU2_VR_Fault_Keep_Unit:
      in:
        or:
          - name: "CPU2_VR_Fault"
          - name: "CPU2_VR_Fault_Shutdown"
        and:
          - name: "CPU2_Off"
            invert: true
      out:
        name: "CPU2_VR_Fault_Shutdown"

  # The following violates multi-processor RESET_N spec
  - RST_LVC3_CPU2_RESET_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            invert: true
      out:
        name: "RST_LVC3_CPU2_RESET"

  - CPU2_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPU2_THERMTRIP"
          - name: "CPU2_VR_PWRGD" # PDG: Ignore THERMTRIP until power is good
            input_stable_usec: 1500
          - name: "CPU2_VR_PWRGD"
      out:
        name: "CPU2_THERMTRIP"

  - H_LVT3_CPU2_THERMTRIP_OUT_N_Enable_Unit:
      in:
        and:
          - name: "pvnn_main_cpu2_On"
          - name: "pvnn_main_cpu2_PowerGood"
      out:
        name: "H_LVT3_CPU2_THERMTRIP_OUT_N_On"

regulators:
  - name: "pvccd_hv_cpu2"
  - name: "pvccfa_ehv_cpu2"
  - name: "pvccfa_ehv_fivra_cpu2"
  - name: "pvccinfaon_cpu2"
  - name: "pvnn_main_cpu2"
  - name: "pvccin_cpu2"
  - name: "pvpp_hbm_cpu2"

