---

# Contains logic to power sequence an Intel Xeon CPU.

inputs:
  # FIVR_FAULT is not read as THERMTRIP_N is driven as well.
  - name: "H_LVT3_CPU3_THERMTRIP_OUT_N"
    signal_name: "H_LVT3_CPU3_THERMTRIP"
    type: "gpio"
    active_low: true
    pullup: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.
    gate_input: true
    gated_idle_high: true

  - name: "H_LVT3_CPU3_MEMTRIP_OUT_N"
    signal_name: "H_LVT3_CPU3_MEMTRIP"
    type: "gpio"
    active_low: true
    pullup: true
    gate_input: true
    gated_idle_high: true

  - name: "system/chassis/motherboard/cpu3"
    type: "dbus_presence"
    pullup: true
    signal_name: "FM_CPU3_SKTOCC"
    description: "CPU3 socket is occupied."

  - name: "PWRGD_CHA_CPU3"
    signal_name: "PWRGD_CHA_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel A power good."

  - name: "PWRGD_CHB_CPU3"
    signal_name: "PWRGD_CHB_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel B power good."

  - name: "PWRGD_CHC_CPU3"
    signal_name: "PWRGD_CHC_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel C power good."

  - name: "PWRGD_CHD_CPU3"
    signal_name: "PWRGD_CHD_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel D power good."

  - name: "PWRGD_CHE_CPU3"
    signal_name: "PWRGD_CHE_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel E power good."

  - name: "PWRGD_CHF_CPU3"
    signal_name: "PWRGD_CHF_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel F power good."

  - name: "PWRGD_CHG_CPU3"
    signal_name: "PWRGD_CHG_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel G power good."

  - name: "PWRGD_CHH_CPU3"
    signal_name: "PWRGD_CHH_CPU3"
    type: "gpio"
    pullup: true
    gate_input: true
    gated_idle_low: true
    gated_output_od_low: true
    description: "CPU3 DDR Channel H power good."

  - name: "FM_CPU3_PKG_ID0"
    signal_name: "FM_CPU3_PKG_ID0"
    type: "gpio"
    pullup: true
    description: "CPU 0 PKGID"

  - name: "FM_CPU3_PKG_ID1"
    signal_name: "FM_CPU3_PKG_ID1"
    type: "gpio"
    pullup: true
    description: "CPU 0 PKGID"

outputs:
  - name: "H_LVT3_CPU3_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_PROCHOT"
    active_low: true
    pullup: true
    description: "CPU3 is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU3_AB_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_AB_DRAM_G"
    pullup: true
    description: "CPU3 memory channel AB power good."

  - name: "PWRGD_LVC3_CPU3_CD_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_CD_DRAM_G"
    pullup: true
    description: "CPU3 memory channel CD power good."

  - name: "PWRGD_LVC3_CPU3_EF_DRAM_G"
    type: "gpio"
    pullup: true
    signal_name: "PWRGD_LVC3_CPU3_EF_DRAM_G"
    description: "CPU3 memory channel EF power good."

  - name: "PWRGD_LVC3_CPU3_GH_DRAM_G"
    type: "gpio"
    pullup: true
    signal_name: "PWRGD_LVC3_CPU3_GH_DRAM_G"
    description: "CPU3 memory channel GH power good."

  - name: "RST_LVC3_CPU3_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU3_RESET"
    active_low: true
    pullup: true
    description: "CPU3 RESET_N"

  - name: "PWRGD_LVC3_CPU3_PWRGOOD"
    type: "gpio"
    pullup: true
    signal_name: "PWRGD_LVC3_CPU3_PWRGOOD"
    description: "Tell CPU3 power good."

  - name: "PWRGD_PLT_AUX_CPU3_LVT3"
    type: "gpio"
    signal_name: "PWRGD_PLT_AUX_CPU3"

  - name: "SEL_SMB_DIMM_CPU3"
    type: "gpio"
    active_low: true
    signal_name: "SEL_SMB_DIMM_CPU3"

  - name: "H_LVT3_CPU3_NMI"
    type: "gpio"
    pullup: true
    signal_name: "CPU3_NMI"

  - name: "FM_CPU3_DISABLE_COD_N"
    type: "gpio"
    pullup: true
    active_low: true
    signal_name: "FM_CPU3_DISABLE_COD"

  - name: "CATERR_CPU3_EN"
    type: "gpio"
    signal_name: "CATERR_CPU3_EN"

immutables:
  - signal_name: "H_LVT3_CPU3_PROCHOT"
    value: false
  - signal_name: "CPU3_NMI"
    value: false
  - signal_name: "FM_CPU3_DISABLE_COD"
    value: false
  - signal_name: "CATERR_CPU3_EN"
    value: true

power_sequencer:
  - PWRGD_LVC3_CPU3_AB_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHA_CPU3"
          - name: "PWRGD_CHB_CPU3"
          - name: "PWRGD_LVC3_CPU3_PWRGOOD_Enabled"
            input_stable_usec: 10000
          - name: "pvccd_hv_cpu3_PowerGood"
      out:
        name: "PWRGD_LVC3_CPU3_AB_DRAM_G"

  - PWRGD_LVC3_CPU3_CD_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHC_CPU3"
          - name: "PWRGD_CHD_CPU3"
          - name: "PWRGD_LVC3_CPU3_PWRGOOD_Enabled"
            input_stable_usec: 10000
          - name: "pvccd_hv_cpu3_PowerGood"
      out:
        name: "PWRGD_LVC3_CPU3_CD_DRAM_G"
  
  - PWRGD_LVC3_CPU3_EF_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHE_CPU3"
          - name: "PWRGD_CHF_CPU3"
          - name: "PWRGD_LVC3_CPU3_PWRGOOD_Enabled"
            input_stable_usec: 10000
          - name: "pvccd_hv_cpu3_PowerGood"
      out:
        name: "PWRGD_LVC3_CPU3_EF_DRAM_G"

  - PWRGD_LVC3_CPU3_GH_DRAM_G_Unit:
      in:
        and:
          - name: "PWRGD_CHG_CPU3"
          - name: "PWRGD_CHH_CPU3"
          - name: "PWRGD_LVC3_CPU3_PWRGOOD_Enabled"
            input_stable_usec: 10000
          - name: "pvccd_hv_cpu3_PowerGood"
      out:
        name: "PWRGD_LVC3_CPU3_GH_DRAM_G"

  - PWRGD_CHA_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_AB_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHA_CPU3_On"

  - PWRGD_CHB_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_AB_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHB_CPU3_On"

  - PWRGD_CHC_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_CD_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHC_CPU3_On"

  - PWRGD_CHD_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_CD_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHD_CPU3_On"

  - PWRGD_CHE_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_EF_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHE_CPU3_On"

  - PWRGD_CHF_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_EF_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHF_CPU3_On"

  - PWRGD_CHG_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_GH_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHG_CPU3_On"

  - PWRGD_CHH_CPU3_Enable_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "PWRGD_LVC3_CPU3_GH_DRAM_G_Enabled"
        and_then_or: true
      out:
        name: "PWRGD_CHH_CPU3_On"

  # DDR & CPU VRs

  # PVCCD_HV must be equal or higher than Vdd at all times.
  - PVCCD_HV_CPU3_Unit:
      in:
        or:
          - name: "pvccfa_ehv_cpu3_Enabled"
          - name: "pvccfa_ehv_fivra_cpu3_Enabled"
          - name: "pvccinfaon_cpu3_Enabled"
        and:
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "DDR_POWER"
        and_then_or: true
      out:
        name: "pvccd_hv_cpu3_On"

  - CPU3_DDR_PWRGD_Unit:
      in:
        and:
          - name: "pvccd_hv_cpu3_PowerGood"
      out:
        name: "CPU3_DDR_PWRGD"

  - SEL_SMB_DIMM_CPU3_Unit:
      in:
        or:
          - name: "CPU_POWER"
          - name: "CPU3_DDR_PWRGD"
            input_stable_usec: 10000
        and:
          - name: "FM_CPU3_SKTOCC"
        and_then_or: false
      out:
        name: "SEL_SMB_DIMM_CPU3"

  - PVCCFA_EHV_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvccd_hv_cpu3_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvccfa_ehv_fivra_cpu3_Enabled"
          - name: "pvccfa_ehv_fivra_cpu3_PowerGood"
            input_stable_usec: 1000
        and_then_or: true
      out:
        name: "pvccfa_ehv_cpu3_On"
  
  - PVCCFA_EHV_FIVRA_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvccd_hv_cpu3_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvccinfaon_cpu3_Enabled"
          - name: "pvccinfaon_cpu3_PowerGood"
            input_stable_usec: 1000
        and_then_or: true
      out:
        name: "pvccfa_ehv_fivra_cpu3_On"

  - PVCCINFAON_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvccfa_ehv_fivra_cpu3_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvnn_main_cpu3_Enabled"
          - name: "pvnn_main_cpu3_PowerGood"
            input_stable_usec: 10000
        and_then_or: true
      out:
        name: "pvccinfaon_cpu3_On"

  - PVNN_MAIN_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvccinfaon_cpu3_PowerGood"
            input_stable_usec: 2
        or:
          - name: "pvccin_cpu3_Enabled"
          - name: "pvccin_cpu3_PowerGood"
            input_stable_usec: 100
        and_then_or: true
      out:
        name: "pvnn_main_cpu3_On"
  
  - PVCCIN_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvnn_main_cpu3_PowerGood"
            input_stable_usec: 2
          - name: "p5v_PowerGood"
            input_stable_usec: 2000
          - name: "p5v_PowerGood"
        or:
          - name: "pvpp_hbm_cpu3_Enabled"
          - name: "pvpp_hbm_cpu3_PowerGood"
            input_stable_usec: 1000
          - name: "PWRGD_CHA_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHB_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHC_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHD_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHE_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHF_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHG_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHH_CPU3_On"
            input_stable_usec: 10000
          - name: "PWRGD_CHA_CPU3_Enabled"
          - name: "PWRGD_CHB_CPU3_Enabled"
          - name: "PWRGD_CHC_CPU3_Enabled"
          - name: "PWRGD_CHD_CPU3_Enabled"
          - name: "PWRGD_CHE_CPU3_Enabled"
          - name: "PWRGD_CHF_CPU3_Enabled"
          - name: "PWRGD_CHG_CPU3_Enabled"
          - name: "PWRGD_CHH_CPU3_Enabled"
        and_then_or: true
      out:
        name: "pvccin_cpu3_On"

  - PVPP_HBM_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_HBM_PRESENT"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvccin_cpu3_PowerGood"
            input_stable_usec: 2
          - name: "PWRGD_CPUPWRGD"
      out:
        name: "pvpp_hbm_cpu3_On"

  - CPU3_HBM_PRESENT_Unit:
      in:
        and:
          - name: "FM_CPU3_PKG_ID0"
            invert: true
          - name: "FM_CPU3_PKG_ID1"
      out:
        name: "CPU3_HBM_PRESENT"

  - CPU3_HBM_Gated_PowerGood_Unit:
      in:
        or:
          - name: "pvpp_hbm_cpu3_PowerGood"
          - name: "CPU3_HBM_PRESENT"
            invert: true
      out:
        name: "CPU3_HBM_Gated_PowerGood"

  - PWRGD_PLT_AUX_CPU3_Unit:
      in:
        and:
          - name: "CPU3_VR_Fault"
            invert: true
          - name: "FM_CPU3_SKTOCC"
        or:
          - name: "CPU3_SYS_PWROK" # Release after SYS_PWROK
            input_stable_usec: 100
          - name: "pvnn_main_cpu3_PowerGood"
            input_stable_usec: 1
        and_then_or: false
      out:
        name: "PWRGD_PLT_AUX_CPU3"

  # All VRs except optional HBM
  - CPU3_VR_PWRGD_Unit:
      in:
        and:
          - name: "pvccfa_ehv_cpu3_PowerGood"
          - name: "pvccfa_ehv_fivra_cpu3_PowerGood"
          - name: "pvccinfaon_cpu3_PowerGood"
          - name: "pvnn_main_cpu3_PowerGood"
          - name: "pvccin_cpu3_PowerGood"
          - name: "pvccfa_ehv_cpu3_Enabled"
          - name: "pvccfa_ehv_fivra_cpu3_Enabled"
          - name: "pvccinfaon_cpu3_Enabled"
          - name: "pvnn_main_cpu3_Enabled"
          - name: "pvccin_cpu3_Enabled"
      out:
        name: "CPU3_VR_PWRGD"

  # Power good & fault handling

  - PWRGD_LVC3_CPU3_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU3_DDR_PWRGD"
            # PDG: 2usec max from VR failure to SYS_PWROK low
          - name: "CPU3_VR_PWRGD" # fast path for emergency shutdown
          - name: "pvccin_cpu3_PowerGood"
            input_stable_usec: 1800
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_DB2000_DEV_EN_Enabled" # Clock buffer enable
            input_stable_usec: 2000 # wait for clocks to be stable
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_HBM_Gated_PowerGood"
      out:
        name: "PWRGD_LVC3_CPU3_PWRGOOD"

  # All VRs except HBM
  - CPU3_SYS_PWROK_Unit:
      in:
        and:
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
          - name: "PWRGD_CHA_CPU3_Enabled"
          - name: "PWRGD_CHB_CPU3_Enabled"
          - name: "PWRGD_CHC_CPU3_Enabled"
          - name: "PWRGD_CHD_CPU3_Enabled"
          - name: "PWRGD_CHE_CPU3_Enabled"
          - name: "PWRGD_CHF_CPU3_Enabled"
          - name: "PWRGD_CHG_CPU3_Enabled"
          - name: "PWRGD_CHH_CPU3_Enabled"
        or:
          - name: "FM_CPU3_SKTOCC"
            invert: true
        and_then_or: true
      out:
        name: "CPU3_SYS_PWROK"
  
  - CPU3_VR_Off_Unit:
      in:
        or:
          - name: "pvccfa_ehv_cpu3_Enabled"
          - name: "pvccfa_ehv_fivra_cpu3_Enabled"
          - name: "pvccinfaon_cpu3_Enabled"
          - name: "pvnn_main_cpu3_Enabled"
          - name: "pvccin_cpu3_Enabled"
          - name: "pvpp_hbm_cpu3_Enabled"
          - name: "pvccfa_ehv_cpu3_PowerGood"
          - name: "pvccfa_ehv_fivra_cpu3_PowerGood"
          - name: "pvccinfaon_cpu3_PowerGood"
          - name: "pvnn_main_cpu3_PowerGood"
          - name: "pvccin_cpu3_PowerGood"
          - name: "pvpp_hbm_cpu3_PowerGood"
          - name: "CPU3_VR_Fault"
      out:
        name: "CPU3_VR_Off"
        active_low: true

  - CPU3_DDR_Off_Unit:
      in:
        or:
          - name: "pvccd_hv_cpu3_Enabled"
      out:
        name: "CPU3_DDR_Off"
        active_low: true
  
  - CPU3_VR_Off_Unit:
      in:
        and:
          - name: "CPU3_DDR_Off"
          - name: "CPU3_VR_Off"
      out:
        name: "CPU3_Off"
    
  - CPU3_VR_Fault_Unit:
      in:
        or:
          - name: "p5v_Fault"
          - name: "pvccfa_ehv_cpu3_Fault"
          - name: "pvccfa_ehv_fivra_cpu3_Fault"
          - name: "pvccinfaon_cpu3_Fault"
          - name: "pvnn_main_cpu3_Fault"
          - name: "pvccin_cpu3_Fault"
          - name: "pvpp_hbm_cpu3_Fault"
          - name: "pvccd_hv_cpu3_Fault"
          - name: "CPU3_THERMTRIP"
        and:
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "CPU3_VR_Fault"

  - CPU3_VR_Fault_Keep_Unit:
      in:
        or:
          - name: "CPU3_VR_Fault"
          - name: "CPU3_VR_Fault_Shutdown"
        and:
          - name: "CPU3_Off"
            invert: true
      out:
        name: "CPU3_VR_Fault_Shutdown"

  # The following violates multi-processor RESET_N spec
  - RST_LVC3_CPU3_RESET_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
      out:
        name: "RST_LVC3_CPU3_RESET"

  - CPU3_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPU3_THERMTRIP"
          - name: "CPU3_VR_PWRGD" # PDG: Ignore THERMTRIP until power is good
            input_stable_usec: 1500
          - name: "CPU3_VR_PWRGD"
      out:
        name: "CPU3_THERMTRIP"

  - H_LVT3_CPU3_THERMTRIP_OUT_N_Enable_Unit:
      in:
        and:
          - name: "pvnn_main_cpu3_On"
          - name: "pvnn_main_cpu3_PowerGood"
      out:
        name: "H_LVT3_CPU3_THERMTRIP_OUT_N_On"

  - CPU3_MEMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPU3_MEMTRIP"
          - name: "CPU3_VR_PWRGD" # PDG: Ignore MEMTRIP until power is good
            input_stable_usec: 1500
          - name: "CPU3_VR_PWRGD"
      out:
        name: "CPU3_MEMTRIP"

  - H_LVT3_CPU3_MEMTRIP_OUT_N_Enable_Unit:
      in:
        and:
          - name: "pvnn_main_cpu3_On"
          - name: "pvnn_main_cpu3_PowerGood"
      out:
        name: "H_LVT3_CPU3_MEMTRIP_OUT_N_On"

regulators:
  - name: "pvccd_hv_cpu3"
  - name: "pvccfa_ehv_cpu3"
  - name: "pvccfa_ehv_fivra_cpu3"
  - name: "pvccinfaon_cpu3"
  - name: "pvnn_main_cpu3"
  - name: "pvccin_cpu3"
  - name: "pvpp_hbm_cpu3"

floating_signals:
  - "H_LVT3_CPU3_MEMTRIP_OUT_N_Enabled"
  - "H_LVT3_CPU3_THERMTRIP_OUT_N_Enabled"
  - "H_LVT3_CPU3_PROCHOT_N_Enabled"
  - "RST_LVC3_CPU3_RESET_N_Enabled"
  - "PWRGD_PLT_AUX_CPU3_LVT3_Enabled"
  - "SEL_SMB_DIMM_CPU3_Enabled"
  - "H_LVT3_CPU3_NMI_Enabled"
  - "FM_CPU3_DISABLE_COD_N_Enabled"
  - "CATERR_CPU3_EN_Enabled"
