---

# Controls power to the two NICs
power_sequencer:
  # Power on if PCH request S0 and user requests S0
  - NIC_POWER_ENABLE_Unit:
      in:
        and:
          - name: "PCH_PWROK"
          - name: "STATE_REQ_HOST_ON"
        or:
          - name: "NIC_POWER_ENABLE_Hold"
        and_then_or: true
      out:
        name: "NIC_POWER_ENABLE"

  # Keep powered until PCH_PWROK goes down again
  - NIC_POWER_ENABLE_Hold_Unit:
      in:
        and:
          - name: "NIC_POWER_ENABLE"
          - name: "PCH_PWROK"
      out:
        name: "NIC_POWER_ENABLE_Hold"

  - pvcore_nic1_Unit:
      in:
        and:
          - name: "NIC_POWER_ENABLE"
          - name: "p3v3_nic_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "p3v3_nic_PowerGood"
        or:
          - name: "p1v2_nic_Enabled"
            input_stable_usec: 1000 # FIXME
          - name: "p1v8_nic_Enabled"
            input_stable_usec: 1000 # FIXME
        and_then_or: true
      out:
        name: "pvcore_nic1_On"

  - pvcore_nic2_Unit:
      in:
        and:
          - name: "NIC_POWER_ENABLE"
          - name: "p3v3_nic_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "p3v3_nic_PowerGood"
        or:
          - name: "p1v2_nic_Enabled"
            input_stable_usec: 1000 # FIXME
          - name: "p1v8_nic_Enabled"
            input_stable_usec: 1000 # FIXME
        and_then_or: true
      out:
        name: "pvcore_nic2_On"

  - p1v2_nic_Unit:
      in:
        and:
          - name: "pvcore_nic1_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "pvcore_nic1_PowerGood"
          - name: "pvcore_nic2_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "pvcore_nic2_PowerGood"
          - name: "p3v3_nic_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "p3v3_nic_PowerGood"
          - name: "NIC_POWER_ENABLE"
        or:
          - name: "p1v8_nic_Enabled"
            input_stable_usec: 1000 # FIXME
        and_then_or: true
      out:
        name: "p1v2_nic_On"

  - p1v8_nic_Unit:
      in:
        and:
          - name: "pvcore_nic1_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "pvcore_nic1_PowerGood"
          - name: "pvcore_nic2_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "pvcore_nic2_PowerGood"
          - name: "p1v2_nic_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "p1v2_nic_PowerGood"
          - name: "p3v3_nic_PowerGood"
            input_stable_usec: 10000 # FIXME
          - name: "p3v3_nic_PowerGood"
          - name: "NIC_POWER_ENABLE"
      out:
        name: "p1v8_nic_On"

  - p3v3_nic_Unit:
      in:
        or:
          - name: "NIC_POWER_ENABLE"
          - name: "pvcore_nic1_Enabled"
            input_stable_usec: 1000 # FIXME
          - name: "pvcore_nic2_Enabled"
            input_stable_usec: 1000 # FIXME
          - name: "p1v2_nic_Enabled"
            input_stable_usec: 1000 # FIXME
          - name: "p1v8_nic_Enabled"
            input_stable_usec: 1000 # FIXME
      out:
        name: "p3v3_nic_On"

  - FM_NIC1_ALLSTANDBY_Unit:
      in:
        and:
          - name: "FM_NIC1_PERST0"
          - name: "FM_NIC1_PERST1"
          - name: "FM_NIC1_PERST2"
          - name: "FM_NIC1_PERST3"
      out:
        name: "FM_NIC1_ALLSTANDBY"

  - FM_NIC2_ALLSTANDBY_Unit:
      in:
        and:
          - name: "FM_NIC2_PERST0"
          - name: "FM_NIC2_PERST1"
          - name: "FM_NIC2_PERST2"
          - name: "FM_NIC2_PERST3"
      out:
        name: "FM_NIC2_ALLSTANDBY"

  - FM_NIC1_PERST0_Unit:
      in:
        or:
          - name: "FM_NIC1_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC1_PERST0"
  - FM_NIC1_PERST1_Unit:
      in:
        or:
          - name: "FM_NIC1_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC1_PERST1"
  - FM_NIC1_PERST2_Unit:
      in:
        or:
          - name: "FM_NIC1_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC1_PERST2"
  - FM_NIC1_PERST3_Unit:
      in:
        or:
          - name: "FM_NIC1_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC1_PERST3"
  - FM_NIC2_PERST0_Unit:
      in:
        or:
          - name: "FM_NIC2_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC2_PERST0"
  - FM_NIC2_PERST1_Unit:
      in:
        or:
          - name: "FM_NIC2_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC2_PERST1"
  - FM_NIC2_PERST2_Unit:
      in:
        or:
          - name: "FM_NIC2_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC2_PERST2"
  - FM_NIC2_PERST3_Unit:
      in:
        or:
          - name: "FM_NIC2_RST"
          - name: "FM_DB2000_DEV_EN"
            invert: true
          - name: "FM_DB2000_DEV_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "FM_NIC2_PERST3"

  # Keep NIC in reset when
  #  - PCH is in reset
  #  - Platform is in S5/S4
  #  - Platform is in reset
  #  - Power rails aren't stable
  - FM_NIC1_Globalreset_Unit:
      in:
        or:
          - name: "NIC_POWER_ENABLE"
            invert: true
          - name: "pvcore_nic1_Fault"
          - name: "pvcore_nic1_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p1v2_nic_Fault"
          - name: "p1v2_nic_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p1v8_nic_Fault"
          - name: "p1v8_nic_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p3v3_nic_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p3v3_nic_Fault"
      out:
        name: "FM_NIC1_RST"

  - FM_NIC2_Globalreset_Unit:
      in:
        or:
          - name: "PCH_PWROK"
            invert: true
          - name: "pvcore_nic2_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "pvcore_nic2_Fault"
          - name: "p1v2_nic_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p1v2_nic_Fault"
          - name: "p1v8_nic_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p1v8_nic_Fault"
          - name: "p3v3_nic_PowerGood"
            invert: true
            input_stable_usec: 100000 # FIXME
          - name: "p3v3_nic_Fault"
      out:
        name: "FM_NIC2_RST"

  - IRQ_NIC2_OVT_SHTDN_Unit:
      in:
        and:
          - name: "FM_NIC2_RST"
            invert: true
      out:
        name: "IRQ_NIC2_OVT_SHTDN_On"

  - IRQ_NIC1_OVT_SHTDN_Unit:
      in:
        and:
          - name: "FM_NIC1_RST"
            invert: true
      out:
        name: "IRQ_NIC1_OVT_SHTDN_On"

  - IRQ_NIC2_OVT_WRNG_Unit:
      in:
        and:
          - name: "FM_NIC2_RST"
            invert: true
      out:
        name: "IRQ_NIC2_OVT_WRNG_On"

  - IRQ_NIC1_OVT_WRNG_Unit:
      in:
        and:
          - name: "FM_NIC1_RST"
            invert: true
      out:
        name: "IRQ_NIC1_OVT_WRNG_On"

regulators:
  - name: "p3v3_nic"
  - name: "pvcore_nic1"
  - name: "pvcore_nic2"
  - name: "p1v2_nic"
  - name: "p1v8_nic"

outputs:
  - name: "FM_NIC1_PERST0_N"
    type: "gpio"
    signal_name: "FM_NIC1_PERST0"
    active_low: true
    pullup: true
    description: "PCIe0 reset"
  - name: "FM_NIC1_PERST1_N"
    type: "gpio"
    signal_name: "FM_NIC1_PERST1"
    active_low: true
    pullup: true
    description: "PCIe1 reset"
  - name: "FM_NIC1_PERST2_N"
    type: "gpio"
    signal_name: "FM_NIC1_PERST2"
    active_low: true
    pullup: true
    description: "PCIe2 reset"
  - name: "FM_NIC1_PERST3_N"
    type: "gpio"
    signal_name: "FM_NIC1_PERST3"
    active_low: true
    pullup: true
    description: "PCIe3 reset"
  - name: "FM_NIC1_ALLSTANDBY_N"
    type: "gpio"
    signal_name: "FM_NIC1_ALLSTANDBY"
    active_low: true
    pullup: true
    description: "All PCIe lanes in reset"
  - name: "FM_NIC1_FLASH_PRSNT"
    type: "gpio"
    signal_name: "FM_NIC1_FLASH_PRSNT"
    description: "Security override."
    open_drain: true
  - name: "FM_NIC2_PERST0_N"
    type: "gpio"
    signal_name: "FM_NIC2_PERST0"
    active_low: true
    pullup: true
    description: "PCIe0 reset"
  - name: "FM_NIC2_PERST1_N"
    type: "gpio"
    signal_name: "FM_NIC2_PERST1"
    active_low: true
    pullup: true
    description: "PCIe1 reset"
  - name: "FM_NIC2_PERST2_N"
    type: "gpio"
    signal_name: "FM_NIC2_PERST2"
    active_low: true
    pullup: true
    description: "PCIe2 reset"
  - name: "FM_NIC2_PERST3_N"
    type: "gpio"
    signal_name: "FM_NIC2_PERST3"
    active_low: true
    pullup: true
    description: "PCIe3 reset"
  - name: "FM_NIC2_ALLSTANDBY_N"
    type: "gpio"
    signal_name: "FM_NIC2_ALLSTANDBY"
    active_low: true
    pullup: true
    description: "All PCIe lanes in reset"
  - name: "FM_NIC2_FLASH_PRSNT"
    type: "gpio"
    signal_name: "FM_NIC2_FLASH_PRSNT"
    description: "Security override."
    open_drain: true
  - name: "FM_NIC1_RST_N"
    type: "gpio"
    signal_name: "FM_NIC1_RST"
    description: "global reset"
    active_low: true
    pullup: true
  - name: "FM_NIC2_RST_N"
    type: "gpio"
    signal_name: "FM_NIC2_RST"
    description: "global reset"
    active_low: true
    pullup: true

inputs:
  - name: "IRQ_NIC1_OVT_WRNG"
    type: "gpio"
    signal_name: "IRQ_NIC1_OVT_WRNG"
    description: "overtemperature warning"
    disablebias: true
    gate_input: true
    gated_idle_low: true
  - name: "IRQ_NIC2_OVT_WRNG"
    type: "gpio"
    signal_name: "IRQ_NIC2_OVT_WRNG"
    description: "overtemperature warning"
    disablebias: true
    gate_input: true
    gated_idle_low: true
  - name: "IRQ_NIC1_OVT_SHTDN"
    type: "gpio"
    signal_name: "IRQ_NIC1_OVT_SHTDN"
    description: "overtemperature shutdown"
    disablebias: true
    gate_input: true
    gated_idle_low: true
  - name: "IRQ_NIC2_OVT_SHTDN"
    type: "gpio"
    signal_name: "IRQ_NIC2_OVT_SHTDN"
    description: "overtemperature shutdown"
    disablebias: true
    gate_input: true
    gated_idle_low: true

floating_signals:
  - "IRQ_NIC1_OVT_WRNG"
  - "IRQ_NIC2_OVT_WRNG"
  - "IRQ_NIC1_OVT_SHTDN"
  - "IRQ_NIC2_OVT_SHTDN"
  - "p3v3_nic_Enabled"

immutables:
  - signal_name: "FM_NIC1_FLASH_PRSNT"
    value: true
  - signal_name: "FM_NIC2_FLASH_PRSNT"
    value: true
