
power_sequencer:
  - RSSD10_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD10_PRESENT"
          - name: "rssd10_FaultKeepOff"
            invert: true
      out:
        name: "rssd10_3v3_On"
  - RSSD10_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD10_PRESENT"
            input_stable_usec: 10000
          - name: "rssd10_FaultKeepOff"
            invert: true
      out:
        name: "rssd10_12v_On"
  - RSSD10_Fault_Unit:
      in:
        and:
          - name: "rssd10_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD10_PRESENT"
        or:
          - name: "rssd10_3v3_Fault"
          - name: "rssd10_12v_Fault"
        and_then_or: true
      out:
        name: "rssd10_FaultKeepOff"
  - RSSD10_Power_En_Unit:
      in:
        and:
          - name: "RSSD10_PRESENT"
            input_stable_usec: 10000
          - name: "rssd10_12v_Fault"
            invert: true
          - name: "rssd10_3v3_Fault"
            invert: true
          - name: "rssd10_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd10_12v_PowerGood"
          - name: "rssd10_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd10_3v3_PowerGood"
      out:
        name: "RSSD10_POWER_EN"
  - RSSD10_SMBRST_Unit:
      in:
        and:
          - name: "RSSD10_POWER_EN"
            invert: true
          - name: "RSSD10_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD10_SMBRST"
  - RSSD10_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD10_SMBRST"
          - name: "RSSD10_PRESENT"
            invert: true
          - name: "RSSD10_POWER_EN"
            invert: true
          - name: "RSSD10_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD10_RESET"
  - RSSD10_LED_Unit:
      in:
        and:
          - name: "RSSD10_RESET"
            invert: true
      out:
        name: "LED_RSSD10"
regulators:
  - name: "rssd10_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd10_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd10"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD10_PRESENT"
outputs:
  - name: "led_rssd10_power"
    type: "led"
    signal_name: "LED_RSSD10"
  - name: "RSSD10_RESET_N"
    type: "gpio"
    signal_name: "RSSD10_RESET"
    active_low: true
  - name: "RSSD10_PWRDIS"
    type: "gpio"
    signal_name: "RSSD10_POWER_EN"
  - name: "RSSD10_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD10_SMBRST"
    active_low: true
floating_signals:
  - "rssd10_3v3_Enabled"
  - "rssd10_12v_Enabled"

