
power_sequencer:
  - RSSD29_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD29_PRESENT"
          - name: "rssd29_FaultKeepOff"
            invert: true
      out:
        name: "rssd29_3v3_On"
  - RSSD29_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD29_PRESENT"
            input_stable_usec: 10000
          - name: "rssd29_FaultKeepOff"
            invert: true
      out:
        name: "rssd29_12v_On"
  - RSSD29_Fault_Unit:
      in:
        and:
          - name: "rssd29_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD29_PRESENT"
        or:
          - name: "rssd29_3v3_Fault"
          - name: "rssd29_12v_Fault"
        and_then_or: true
      out:
        name: "rssd29_FaultKeepOff"
  - RSSD29_Power_En_Unit:
      in:
        and:
          - name: "RSSD29_PRESENT"
            input_stable_usec: 10000
          - name: "rssd29_12v_Fault"
            invert: true
          - name: "rssd29_3v3_Fault"
            invert: true
          - name: "rssd29_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd29_12v_PowerGood"
          - name: "rssd29_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd29_3v3_PowerGood"
      out:
        name: "RSSD29_POWER_EN"
  - RSSD29_SMBRST_Unit:
      in:
        and:
          - name: "RSSD29_PWRDIS_Enabled"
            invert: true
          - name: "RSSD29_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD29_SMBRST"
  - RSSD29_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD29_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD29_PRESENT"
          - name: "RSSD29_POWER_EN"
          - name: "RSSD29_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD29_RESET"
        active_low: true
  - RSSD29_LED_Unit:
      in:
        and:
          - name: "RSSD29_RESET"
            invert: true
      out:
        name: "LED_RSSD29"
regulators:
  - name: "rssd29_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd29_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd29"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD29_PRESENT"
outputs:
  - name: "led_rssd29_power"
    type: "led"
    signal_name: "LED_RSSD29"
  - name: "RSSD29_RESET_N"
    type: "gpio"
    signal_name: "RSSD29_RESET"
    active_low: true
  - name: "RSSD29_PWRDIS"
    type: "gpio"
    signal_name: "RSSD29_POWER_EN"
    active_low: true
  - name: "RSSD29_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD29_SMBRST"
    active_low: true
floating_signals:
  - "rssd29_3v3_Enabled"
  - "rssd29_12v_Enabled"
  - "RSSD29_RESET_N_Enabled"

