
power_sequencer:
  - RSSD04_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD04_PRESENT"
          - name: "rssd04_FaultKeepOff"
            invert: true
      out:
        name: "rssd04_3v3_On"
  - RSSD04_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD04_PRESENT"
            input_stable_usec: 10000
          - name: "rssd04_FaultKeepOff"
            invert: true
      out:
        name: "rssd04_12v_On"
  - RSSD04_Fault_Unit:
      in:
        and:
          - name: "rssd04_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD04_PRESENT"
        or:
          - name: "rssd04_3v3_Fault"
          - name: "rssd04_12v_Fault"
        and_then_or: true
      out:
        name: "rssd04_FaultKeepOff"
  - RSSD04_Power_En_Unit:
      in:
        and:
          - name: "RSSD04_PRESENT"
            input_stable_usec: 10000
          - name: "rssd04_12v_Fault"
            invert: true
          - name: "rssd04_3v3_Fault"
            invert: true
          - name: "rssd04_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd04_12v_PowerGood"
          - name: "rssd04_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd04_3v3_PowerGood"
      out:
        name: "RSSD04_POWER_EN"
  - RSSD04_SMBRST_Unit:
      in:
        and:
          - name: "RSSD04_POWER_EN"
            invert: true
          - name: "RSSD04_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD04_SMBRST"
  - RSSD04_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD04_SMBRST"
          - name: "RSSD04_PRESENT"
            invert: true
          - name: "RSSD04_POWER_EN"
            invert: true
          - name: "RSSD04_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD04_RESET"
  - RSSD04_LED_Unit:
      in:
        and:
          - name: "RSSD04_RESET"
            invert: true
      out:
        name: "LED_RSSD04"
regulators:
  - name: "rssd04_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd04_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd04"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD04_PRESENT"
outputs:
  - name: "led_rssd04_power"
    type: "led"
    signal_name: "LED_RSSD04"
  - name: "RSSD04_RESET_N"
    type: "gpio"
    signal_name: "RSSD04_RESET"
    active_low: true
  - name: "RSSD04_PWRDIS"
    type: "gpio"
    signal_name: "RSSD04_POWER_EN"
    active_low: true
  - name: "RSSD04_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD04_SMBRST"
    active_low: true
floating_signals:
  - "rssd04_3v3_Enabled"
  - "rssd04_12v_Enabled"

