
power_sequencer:
  - RSSD12_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD12_PRESENT"
          - name: "rssd12_FaultKeepOff"
            invert: true
      out:
        name: "rssd12_3v3_On"
  - RSSD12_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD12_PRESENT"
            input_stable_usec: 10000
          - name: "rssd12_FaultKeepOff"
            invert: true
      out:
        name: "rssd12_12v_On"
  - RSSD12_Fault_Unit:
      in:
        and:
          - name: "rssd12_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD12_PRESENT"
        or:
          - name: "rssd12_3v3_Fault"
          - name: "rssd12_12v_Fault"
        and_then_or: true
      out:
        name: "rssd12_FaultKeepOff"
  - RSSD12_Power_En_Unit:
      in:
        and:
          - name: "RSSD12_PRESENT"
            input_stable_usec: 10000
          - name: "rssd12_12v_Fault"
            invert: true
          - name: "rssd12_3v3_Fault"
            invert: true
          - name: "rssd12_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd12_12v_PowerGood"
          - name: "rssd12_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd12_3v3_PowerGood"
      out:
        name: "RSSD12_POWER_EN"
  - RSSD12_SMBRST_Unit:
      in:
        and:
          - name: "RSSD12_POWER_EN"
            invert: true
          - name: "RSSD12_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD12_SMBRST"
  - RSSD12_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD12_SMBRST"
          - name: "RSSD12_PRESENT"
            invert: true
          - name: "RSSD12_POWER_EN"
            invert: true
          - name: "RSSD12_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD12_RESET"
  - RSSD12_LED_Unit:
      in:
        and:
          - name: "RSSD12_RESET"
            invert: true
      out:
        name: "LED_RSSD12"
regulators:
  - name: "rssd12_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd12_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd12"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD12_PRESENT"
outputs:
  - name: "led_rssd12_power"
    type: "led"
    signal_name: "LED_RSSD12"
  - name: "RSSD12_RESET_N"
    type: "gpio"
    signal_name: "RSSD12_RESET"
    active_low: true
  - name: "RSSD12_PWRDIS"
    type: "gpio"
    signal_name: "RSSD12_POWER_EN"
  - name: "RSSD12_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD12_SMBRST"
    active_low: true
floating_signals:
  - "rssd12_3v3_Enabled"
  - "rssd12_12v_Enabled"

