
power_sequencer:
  - RSSD09_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD09_PRESENT"
          - name: "rssd09_FaultKeepOff"
            invert: true
      out:
        name: "rssd09_3v3_On"
  - RSSD09_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD09_PRESENT"
            input_stable_usec: 10000
          - name: "rssd09_FaultKeepOff"
            invert: true
      out:
        name: "rssd09_12v_On"
  - RSSD09_Fault_Unit:
      in:
        and:
          - name: "rssd09_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD09_PRESENT"
        or:
          - name: "rssd09_3v3_Fault"
          - name: "rssd09_12v_Fault"
        and_then_or: true
      out:
        name: "rssd09_FaultKeepOff"        
  - RSSD09_Power_En_Unit:
      in:
        and:
          - name: "RSSD09_PRESENT"
            input_stable_usec: 10000
          - name: "rssd09_12v_Fault"
            invert: true
          - name: "rssd09_3v3_Fault"
            invert: true
          - name: "rssd09_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd09_12v_PowerGood"
          - name: "rssd09_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd09_3v3_PowerGood"
      out:
        name: "RSSD09_POWER_EN"
  - RSSD09_SMBRST_Unit:
      in:
        and:
          - name: "RSSD09_POWER_EN"
          - name: "RSSD09_POWER_EN"
            input_stable_usec: 10000
      out:
        name: "RSSD09_SMBRST"
  - RSSD09_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD09_SMBRST"
          - name: "RSSD09_PRESENT"
            invert: true
          - name: "RSSD09_POWER_EN"
            invert: true
          - name: "RSSD09_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR1_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD09_RESET"
  - RSSD09_LED_Unit:
      in:
        and:
          - name: "RSSD09_RESET"
            invert: true
      out:
        name: "LED_RSSD09"
regulators:
  - name: "rssd09_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd09_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd09"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD09_PRESENT"
outputs:
  - name: "led_rssd09_power"
    type: "led"
    signal_name: "LED_RSSD09"
  - name: "RSSD09_RESET_N"
    type: "gpio"
    signal_name: "RSSD09_RESET"
    active_low: true
  - name: "RSSD09_PWRDIS"
    type: "gpio"
    signal_name: "RSSD09_POWER_EN"
    active_low: true
  - name: "RSSD09_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD09_SMBRST"
    active_low: true
floating_signals:
  - "rssd09_3v3_Enabled"
  - "rssd09_12v_Enabled"

