
power_sequencer:
  - RSSD02_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD02_PRESENT"
          - name: "rssd02_FaultKeepOff"
            invert: true
      out:
        name: "rssd02_3v3_On"
  - RSSD02_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD02_PRESENT"
            input_stable_usec: 10000
          - name: "rssd02_FaultKeepOff"
            invert: true
      out:
        name: "rssd02_12v_On"
  - RSSD02_Fault_Unit:
      in:
        and:
          - name: "rssd02_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD02_PRESENT"
        or:
          - name: "rssd02_3v3_Fault"
          - name: "rssd02_12v_Fault"
        and_then_or: true
      out:
        name: "rssd02_FaultKeepOff"
  - RSSD02_Power_En_Unit:
      in:
        and:
          - name: "RSSD02_PRESENT"
            input_stable_usec: 10000
          - name: "rssd02_12v_Fault"
            invert: true
          - name: "rssd02_3v3_Fault"
            invert: true
          - name: "rssd02_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd02_12v_PowerGood"
          - name: "rssd02_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd02_3v3_PowerGood"
      out:
        name: "RSSD02_POWER_EN"
  - RSSD02_SMBRST_Unit:
      in:
        and:
          - name: "RSSD02_PWRDIS_Enabled"
            invert: true
          - name: "RSSD02_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD02_SMBRST"
  - RSSD02_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD02_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD02_PRESENT"
          - name: "RSSD02_POWER_EN"
          - name: "RSSD02_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR0_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR0_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD02_RESET"
        active_low: true
  - RSSD02_LED_Unit:
      in:
        and:
          - name: "RSSD02_RESET"
            invert: true
      out:
        name: "LED_RSSD02"
regulators:
  - name: "rssd02_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd02_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd02"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD02_PRESENT"
outputs:
  - name: "led_rssd02_power"
    type: "led"
    signal_name: "LED_RSSD02"
  - name: "RSSD02_RESET_N"
    type: "gpio"
    signal_name: "RSSD02_RESET"
    active_low: true
  - name: "RSSD02_PWRDIS"
    type: "gpio"
    signal_name: "RSSD02_POWER_EN"
    active_low: true
  - name: "RSSD02_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD02_SMBRST"
    active_low: true
floating_signals:
  - "rssd02_3v3_Enabled"
  - "rssd02_12v_Enabled"
  - "RSSD02_RESET_N_Enabled"

