
power_sequencer:
  - RSSD32_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD32_PRESENT"
          - name: "rssd32_FaultKeepOff"
            invert: true
      out:
        name: "rssd32_3v3_On"
  - RSSD32_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD32_PRESENT"
            input_stable_usec: 10000
          - name: "rssd32_FaultKeepOff"
            invert: true
      out:
        name: "rssd32_12v_On"
  - RSSD32_Fault_Unit:
      in:
        and:
          - name: "rssd32_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD32_PRESENT"
        or:
          - name: "rssd32_3v3_Fault"
          - name: "rssd32_12v_Fault"
        and_then_or: true
      out:
        name: "rssd32_FaultKeepOff"
  - RSSD32_Power_En_Unit:
      in:
        and:
          - name: "RSSD32_PRESENT"
            input_stable_usec: 10000
          - name: "rssd32_12v_Fault"
            invert: true
          - name: "rssd32_3v3_Fault"
            invert: true
          - name: "rssd32_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd32_12v_PowerGood"
          - name: "rssd32_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd32_3v3_PowerGood"
      out:
        name: "RSSD32_POWER_EN"
  - RSSD32_SMBRST_Unit:
      in:
        and:
          - name: "RSSD32_PWRDIS_Enabled"
            invert: true
          - name: "RSSD32_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD32_SMBRST"
  - RSSD32_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD32_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD32_PRESENT"
          - name: "RSSD32_POWER_EN"
          - name: "RSSD32_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD32_RESET"
        active_low: true
  - RSSD32_LED_Unit:
      in:
        and:
          - name: "RSSD32_RESET"
            invert: true
      out:
        name: "LED_RSSD32"
regulators:
  - name: "rssd32_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd32_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd32"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD32_PRESENT"
outputs:
  - name: "led_rssd32_power"
    type: "led"
    signal_name: "LED_RSSD32"
  - name: "RSSD32_RESET_N"
    type: "gpio"
    signal_name: "RSSD32_RESET"
    active_low: true
  - name: "RSSD32_PWRDIS"
    type: "gpio"
    signal_name: "RSSD32_POWER_EN"
    active_low: true
  - name: "RSSD32_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD32_SMBRST"
    active_low: true
floating_signals:
  - "rssd32_3v3_Enabled"
  - "rssd32_12v_Enabled"
  - "RSSD32_RESET_N_Enabled"
