
power_sequencer:
  - RSSD18_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD18_PRESENT"
          - name: "rssd18_FaultKeepOff"
            invert: true
      out:
        name: "rssd18_3v3_On"
  - RSSD18_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD18_PRESENT"
            input_stable_usec: 10000
          - name: "rssd18_FaultKeepOff"
            invert: true
      out:
        name: "rssd18_12v_On"
  - RSSD18_Fault_Unit:
      in:
        and:
          - name: "rssd18_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD18_PRESENT"
        or:
          - name: "rssd18_3v3_Fault"
          - name: "rssd18_12v_Fault"
        and_then_or: true
      out:
        name: "rssd18_FaultKeepOff"
  - RSSD18_Power_En_Unit:
      in:
        and:
          - name: "RSSD18_PRESENT"
            input_stable_usec: 10000
          - name: "rssd18_12v_Fault"
            invert: true
          - name: "rssd18_3v3_Fault"
            invert: true
          - name: "rssd18_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd18_12v_PowerGood"
          - name: "rssd18_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd18_3v3_PowerGood"
      out:
        name: "RSSD18_POWER_EN"
  - RSSD18_SMBRST_Unit:
      in:
        and:
          - name: "RSSD18_PWRDIS_Enabled"
            invert: true
          - name: "RSSD18_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD18_SMBRST"
  - RSSD17_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD18_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD18_PRESENT"
          - name: "RSSD18_POWER_EN"
          - name: "RSSD18_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU2_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD18_RESET"
        active_low: true
  - RSSD18_LED_Unit:
      in:
        and:
          - name: "RSSD18_POWER_EN"
      out:
        name: "LED_RSSD18"
regulators:
  - name: "rssd18_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd18_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd18"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD18_PRESENT"
outputs:
  - name: "led_rssd18_power"
    type: "led"
    signal_name: "LED_RSSD18"
  - name: "RSSD18_RESET_N"
    type: "gpio"
    signal_name: "RSSD18_RESET"
    active_low: true
  - name: "RSSD18_PWRDIS"
    type: "gpio"
    signal_name: "RSSD18_POWER_EN"
    active_low: true
  - name: "RSSD18_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD18_SMBRST"
    active_low: true
floating_signals:
  - "rssd18_3v3_Enabled"
  - "rssd18_12v_Enabled"
  - "rssd18_3v3_IsDummy"
  - "rssd18_12v_IsDummy"
  - "RSSD18_RESET_N_Enabled"

