
power_sequencer:
  - RSSD9_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD9_PRESENT"
          - name: "rssd9_FaultKeepOff"
            invert: true
      out:
        name: "rssd9_3v3_On"
  - RSSD9_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD9_PRESENT"
            input_stable_usec: 10000
          - name: "rssd9_FaultKeepOff"
            invert: true
      out:
        name: "rssd9_12v_On"
  - RSSD9_Fault_Unit:
      in:
        and:
          - name: "rssd9_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD9_PRESENT"
        or:
          - name: "rssd9_3v3_Fault"
          - name: "rssd9_12v_Fault"
        and_then_or: true
      out:
        name: "rssd9_FaultKeepOff"
  - RSSD9_Power_En_Unit:
      in:
        and:
          - name: "RSSD9_PRESENT"
            input_stable_usec: 10000
          - name: "rssd9_12v_Fault"
            invert: true
          - name: "rssd9_3v3_Fault"
            invert: true
          - name: "rssd9_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd9_12v_PowerGood"
          - name: "rssd9_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd9_3v3_PowerGood"
      out:
        name: "RSSD9_POWER_EN"
  - RSSD9_SMBRST_Unit:
      in:
        and:
          - name: "RSSD9_POWER_EN"
            invert: true
          - name: "RSSD9_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD9_SMBRST"
  - RSSD9_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD9_SMBRST"
          - name: "RSSD9_PRESENT"
            invert: true
          - name: "RSSD9_POWER_EN"
            invert: true
          - name: "RSSD9_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD9_RESET"
  - RSSD9_LED_Unit:
      in:
        and:
          - name: "RSSD9_RESET"
            invert: true
      out:
        name: "LED_RSSD9"
regulators:
  - name: "rssd9_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd9_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd9"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD9_PRESENT"
outputs:
  - name: "led_rssd9_power"
    type: "led"
    signal_name: "LED_RSSD9"
  - name: "RSSD9_RESET_N"
    type: "gpio"
    signal_name: "RSSD9_RESET"
    active_low: true
  - name: "RSSD9_PWRDIS"
    type: "gpio"
    signal_name: "RSSD9_POWER_EN"
  - name: "RSSD9_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD9_SMBRST"
    active_low: true
floating_signals:
  - "rssd9_3v3_Enabled"
  - "rssd9_12v_Enabled"

