
power_sequencer:
  - RSSD08_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD08_PRESENT"
          - name: "rssd08_FaultKeepOff"
            invert: true
      out:
        name: "rssd08_3v3_On"
  - RSSD08_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD08_PRESENT"
            input_stable_usec: 10000
          - name: "rssd08_FaultKeepOff"
            invert: true
      out:
        name: "rssd08_12v_On"
  - RSSD08_Fault_Unit:
      in:
        and:
          - name: "rssd08_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD08_PRESENT"
        or:
          - name: "rssd08_3v3_Fault"
          - name: "rssd08_12v_Fault"
        and_then_or: true
      out:
        name: "rssd08_FaultKeepOff"
  - RSSD08_Power_En_Unit:
      in:
        and:
          - name: "RSSD08_PRESENT"
            input_stable_usec: 10000
          - name: "rssd08_12v_Fault"
            invert: true
          - name: "rssd08_3v3_Fault"
            invert: true
          - name: "rssd08_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd08_12v_PowerGood"
          - name: "rssd08_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd08_3v3_PowerGood"
      out:
        name: "RSSD08_POWER_EN"
  - RSSD08_SMBRST_Unit:
      in:
        and:
          - name: "RSSD08_POWER_EN"
            invert: true
          - name: "RSSD08_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD08_SMBRST"
  - RSSD08_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD08_SMBRST"
          - name: "RSSD08_PRESENT"
            invert: true
          - name: "RSSD08_POWER_EN"
            invert: true
          - name: "RSSD08_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD08_RESET"
  - RSSD08_LED_Unit:
      in:
        and:
          - name: "RSSD08_RESET"
            invert: true
      out:
        name: "LED_RSSD08"
regulators:
  - name: "rssd08_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd08_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd08"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD08_PRESENT"
outputs:
  - name: "led_rssd08_power"
    type: "led"
    signal_name: "LED_RSSD08"
  - name: "RSSD08_RESET_N"
    type: "gpio"
    signal_name: "RSSD08_RESET"
    active_low: true
  - name: "RSSD08_PWRDIS"
    type: "gpio"
    signal_name: "RSSD08_POWER_EN"
  - name: "RSSD08_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD08_SMBRST"
    active_low: true
floating_signals:
  - "rssd08_3v3_Enabled"
  - "rssd08_12v_Enabled"

