
power_sequencer:
  - RSSD03_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD03_PRESENT"
          - name: "rssd03_FaultKeepOff"
            invert: true
      out:
        name: "rssd03_3v3_On"
  - RSSD03_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD03_PRESENT"
            input_stable_usec: 10000
          - name: "rssd03_FaultKeepOff"
            invert: true
      out:
        name: "rssd03_12v_On"
  - RSSD03_Fault_Unit:
      in:
        and:
          - name: "rssd03_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD03_PRESENT"
        or:
          - name: "rssd03_3v3_Fault"
          - name: "rssd03_12v_Fault"
        and_then_or: true
      out:
        name: "rssd03_FaultKeepOff"
  - RSSD03_Power_En_Unit:
      in:
        and:
          - name: "RSSD03_PRESENT"
            input_stable_usec: 10000
          - name: "rssd03_12v_Fault"
            invert: true
          - name: "rssd03_3v3_Fault"
            invert: true
          - name: "rssd03_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd03_12v_PowerGood"
          - name: "rssd03_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd03_3v3_PowerGood"
      out:
        name: "RSSD03_POWER_EN"
  - RSSD03_SMBRST_Unit:
      in:
        and:
          - name: "RSSD03_POWER_EN"
            invert: true
          - name: "RSSD03_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD03_SMBRST"
  - RSSD03_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD03_SMBRST"
          - name: "RSSD03_PRESENT"
            invert: true
          - name: "RSSD03_POWER_EN"
            invert: true
          - name: "RSSD03_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD03_RESET"
  - RSSD03_LED_Unit:
      in:
        and:
          - name: "RSSD03_RESET"
            invert: true
      out:
        name: "LED_RSSD03"
regulators:
  - name: "rssd03_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd03_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd03"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD03_PRESENT"
outputs:
  - name: "led_rssd03_power"
    type: "led"
    signal_name: "LED_RSSD03"
  - name: "RSSD03_RESET_N"
    type: "gpio"
    signal_name: "RSSD03_RESET"
    active_low: true
  - name: "RSSD03_PWRDIS"
    type: "gpio"
    signal_name: "RSSD03_POWER_EN"
  - name: "RSSD03_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD03_SMBRST"
    active_low: true
floating_signals:
  - "rssd03_3v3_Enabled"
  - "rssd03_12v_Enabled"

