
power_sequencer:
  - RSSD30_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD30_PRESENT"
          - name: "rssd30_FaultKeepOff"
            invert: true
      out:
        name: "rssd30_3v3_On"
  - RSSD30_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD30_PRESENT"
            input_stable_usec: 10000
          - name: "rssd30_FaultKeepOff"
            invert: true
      out:
        name: "rssd30_12v_On"
  - RSSD30_Fault_Unit:
      in:
        and:
          - name: "rssd30_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD30_PRESENT"
        or:
          - name: "rssd30_3v3_Fault"
          - name: "rssd30_12v_Fault"
        and_then_or: true
      out:
        name: "rssd30_FaultKeepOff"
  - RSSD30_Power_En_Unit:
      in:
        and:
          - name: "RSSD30_PRESENT"
            input_stable_usec: 10000
          - name: "rssd30_12v_Fault"
            invert: true
          - name: "rssd30_3v3_Fault"
            invert: true
          - name: "rssd30_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd30_12v_PowerGood"
          - name: "rssd30_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd30_3v3_PowerGood"
      out:
        name: "RSSD30_POWER_EN"
  - RSSD30_SMBRST_Unit:
      in:
        and:
          - name: "RSSD30_PWRDIS_Enabled"
            invert: true
          - name: "RSSD30_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD30_SMBRST"
  - RSSD30_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD30_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD30_PRESENT"
          - name: "RSSD30_POWER_EN"
          - name: "RSSD30_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD30_RESET"
        active_low: true
  - RSSD30_LED_Unit:
      in:
        and:
          - name: "RSSD30_POWER_EN"
      out:
        name: "LED_RSSD30"
regulators:
  - name: "rssd30_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd30_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd30"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD30_PRESENT"
outputs:
  - name: "led_rssd30_power"
    type: "led"
    signal_name: "LED_RSSD30"
  - name: "RSSD30_RESET_N"
    type: "gpio"
    signal_name: "RSSD30_RESET"
    active_low: true
  - name: "RSSD30_PWRDIS"
    type: "gpio"
    signal_name: "RSSD30_POWER_EN"
    active_low: true
  - name: "RSSD30_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD30_SMBRST"
    active_low: true
floating_signals:
  - "rssd30_3v3_Enabled"
  - "rssd30_12v_Enabled"
  - "rssd30_3v3_IsDummy"
  - "rssd30_12v_IsDummy"
  - "RSSD30_RESET_N_Enabled"

