
power_sequencer:
  - RSSD16_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD16_PRESENT"
          - name: "rssd16_FaultKeepOff"
            invert: true
      out:
        name: "rssd16_3v3_On"
  - RSSD16_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD16_PRESENT"
            input_stable_usec: 10000
          - name: "rssd16_FaultKeepOff"
            invert: true
      out:
        name: "rssd16_12v_On"
  - RSSD16_Fault_Unit:
      in:
        and:
          - name: "rssd16_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD16_PRESENT"
        or:
          - name: "rssd16_3v3_Fault"
          - name: "rssd16_12v_Fault"
        and_then_or: true
      out:
        name: "rssd16_FaultKeepOff"
  - RSSD16_Power_En_Unit:
      in:
        and:
          - name: "RSSD16_PRESENT"
            input_stable_usec: 10000
          - name: "rssd16_12v_Fault"
            invert: true
          - name: "rssd16_3v3_Fault"
            invert: true
          - name: "rssd16_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd16_12v_PowerGood"
          - name: "rssd16_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd16_3v3_PowerGood"
      out:
        name: "RSSD16_POWER_EN"
  - RSSD16_SMBRST_Unit:
      in:
        and:
          - name: "RSSD16_POWER_EN"
            invert: true
          - name: "RSSD16_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD16_SMBRST"
  - RSSD16_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD16_SMBRST"
          - name: "RSSD16_PRESENT"
            invert: true
          - name: "RSSD16_POWER_EN"
            invert: true
          - name: "RSSD16_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR0_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU0_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD16_RESET"
  - RSSD16_LED_Unit:
      in:
        and:
          - name: "RSSD16_RESET"
            invert: true
      out:
        name: "LED_RSSD16"
regulators:
  - name: "rssd16_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd16_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd16"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD16_PRESENT"
outputs:
  - name: "led_rssd16_power"
    type: "led"
    signal_name: "LED_RSSD16"
  - name: "RSSD16_RESET_N"
    type: "gpio"
    signal_name: "RSSD16_RESET"
    active_low: true
  - name: "RSSD16_PWRDIS"
    type: "gpio"
    signal_name: "RSSD16_POWER_EN"
  - name: "RSSD16_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD16_SMBRST"
    active_low: true
floating_signals:
  - "rssd16_3v3_Enabled"
  - "rssd16_12v_Enabled"

