
power_sequencer:
  - RSSD27_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD27_PRESENT"
          - name: "rssd27_FaultKeepOff"
            invert: true
      out:
        name: "rssd27_3v3_On"
  - RSSD27_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD27_PRESENT"
            input_stable_usec: 10000
          - name: "rssd27_FaultKeepOff"
            invert: true
      out:
        name: "rssd27_12v_On"
  - RSSD27_Fault_Unit:
      in:
        and:
          - name: "rssd27_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD27_PRESENT"
        or:
          - name: "rssd27_3v3_Fault"
          - name: "rssd27_12v_Fault"
        and_then_or: true
      out:
        name: "rssd27_FaultKeepOff"
  - RSSD27_Power_En_Unit:
      in:
        and:
          - name: "RSSD27_PRESENT"
            input_stable_usec: 10000
          - name: "rssd27_12v_Fault"
            invert: true
          - name: "rssd27_3v3_Fault"
            invert: true
          - name: "rssd27_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd27_12v_PowerGood"
          - name: "rssd27_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd27_3v3_PowerGood"
      out:
        name: "RSSD27_POWER_EN"
  - RSSD27_SMBRST_Unit:
      in:
        and:
          - name: "RSSD27_PWRDIS_Enabled"
            invert: true
          - name: "RSSD27_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD27_SMBRST"
  - RSSD27_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD27_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD27_PRESENT"
          - name: "RSSD27_POWER_EN"
          - name: "RSSD27_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR1_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD27_RESET"
        active_low: true
  - RSSD27_LED_Unit:
      in:
        and:
          - name: "RSSD27_POWER_EN"
      out:
        name: "LED_RSSD27"
regulators:
  - name: "rssd27_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd27_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd27"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD27_PRESENT"
outputs:
  - name: "led_rssd27_power"
    type: "led"
    signal_name: "LED_RSSD27"
  - name: "RSSD27_RESET_N"
    type: "gpio"
    signal_name: "RSSD27_RESET"
    active_low: true
  - name: "RSSD27_PWRDIS"
    type: "gpio"
    signal_name: "RSSD27_POWER_EN"
    active_low: true
  - name: "RSSD27_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD27_SMBRST"
    active_low: true
floating_signals:
  - "rssd27_3v3_Enabled"
  - "rssd27_12v_Enabled"
  - "RSSD27_RESET_N_Enabled"

