
power_sequencer:
  - RSSD31_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD31_PRESENT"
          - name: "rssd31_FaultKeepOff"
            invert: true
      out:
        name: "rssd31_3v3_On"
  - RSSD31_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD31_PRESENT"
            input_stable_usec: 10000
          - name: "rssd31_FaultKeepOff"
            invert: true
      out:
        name: "rssd31_12v_On"
  - RSSD31_Fault_Unit:
      in:
        and:
          - name: "rssd31_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD31_PRESENT"
        or:
          - name: "rssd31_3v3_Fault"
          - name: "rssd31_12v_Fault"
        and_then_or: true
      out:
        name: "rssd31_FaultKeepOff"
  - RSSD31_Power_En_Unit:
      in:
        and:
          - name: "RSSD31_PRESENT"
            input_stable_usec: 10000
          - name: "rssd31_12v_Fault"
            invert: true
          - name: "rssd31_3v3_Fault"
            invert: true
          - name: "rssd31_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd31_12v_PowerGood"
          - name: "rssd31_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd31_3v3_PowerGood"
      out:
        name: "RSSD31_POWER_EN"
  - RSSD31_SMBRST_Unit:
      in:
        and:
          - name: "RSSD31_POWER_EN"
            invert: true
          - name: "RSSD31_POWER_EN"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD31_SMBRST"
  - RSSD31_Reset_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "SYS_PWROK"
            invert: true
          - name: "RSSD31_SMBRST"
          - name: "RSSD31_PRESENT"
            invert: true
          - name: "RSSD31_POWER_EN"
            invert: true
          - name: "RSSD31_POWER_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
          - name: "FM_SSD_CLK_DRVR1_EN"
            invert: true
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU1_PWRGOOD"
            invert: true
            input_stable_usec: 100000
      out:
        name: "RSSD31_RESET"
  - RSSD31_LED_Unit:
      in:
        and:
          - name: "RSSD31_RESET"
            invert: true
      out:
        name: "LED_RSSD31"
regulators:
  - name: "rssd31_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd31_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd31"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD31_PRESENT"
outputs:
  - name: "led_rssd31_power"
    type: "led"
    signal_name: "LED_RSSD31"
  - name: "RSSD31_RESET_N"
    type: "gpio"
    signal_name: "RSSD31_RESET"
    active_low: true
  - name: "RSSD31_PWRDIS"
    type: "gpio"
    signal_name: "RSSD31_POWER_EN"
  - name: "RSSD31_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD31_SMBRST"
    active_low: true
floating_signals:
  - "rssd31_3v3_Enabled"
  - "rssd31_12v_Enabled"

