
power_sequencer:
  - RSSD07_3v3_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD07_PRESENT"
          - name: "rssd07_FaultKeepOff"
            invert: true
      out:
        name: "rssd07_3v3_On"
  - RSSD07_12v_Enable_Unit:
      in:
        and:
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD07_PRESENT"
            input_stable_usec: 10000
          - name: "rssd07_FaultKeepOff"
            invert: true
      out:
        name: "rssd07_12v_On"
  - RSSD07_Fault_Unit:
      in:
        and:
          - name: "rssd07_FaultKeepOff"
          - name: "SYS_PWROK"
            input_stable_usec: 10000
          - name: "RSSD07_PRESENT"
        or:
          - name: "rssd07_3v3_Fault"
          - name: "rssd07_12v_Fault"
        and_then_or: true
      out:
        name: "rssd07_FaultKeepOff"
  - RSSD07_Power_En_Unit:
      in:
        and:
          - name: "RSSD07_PRESENT"
            input_stable_usec: 10000
          - name: "rssd07_12v_Fault"
            invert: true
          - name: "rssd07_3v3_Fault"
            invert: true
          - name: "rssd07_12v_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd07_12v_PowerGood"
          - name: "rssd07_3v3_PowerGood"
            input_stable_usec: 5000000
          - name: "rssd07_3v3_PowerGood"
      out:
        name: "RSSD07_POWER_EN"
  - RSSD07_SMBRST_Unit:
      in:
        and:
          - name: "RSSD07_PWRDIS_Enabled"
            invert: true
          - name: "RSSD07_PWRDIS_Enabled"
            input_stable_usec: 10000
            invert: true
      out:
        name: "RSSD07_SMBRST"
  - RSSD07_Reset_Unit:
      in:
        and:
          - name: "PLTRST"
            invert: true
          - name: "SYS_PWROK"
          - name: "RSSD07_SMBRST_N_Enabled"
            invert: true
          - name: "RSSD07_PRESENT"
          - name: "RSSD07_POWER_EN"
          - name: "RSSD07_PWRDIS_Enabled"
            input_stable_usec: 100000
          - name: "PWRGD_LVC3_CPU3_PWRGOOD_Enabled"
          - name: "FM_SSD_CLK_DRVR0_EN_Enabled"
          - name: "FM_SSD_CLK_DRVR0_EN_Enabled"
            input_stable_usec: 100000
      out:
        name: "RSSD07_RESET"
        active_low: true
  - RSSD07_LED_Unit:
      in:
        and:
          - name: "RSSD07_POWER_EN"
      out:
        name: "LED_RSSD07"
regulators:
  - name: "rssd07_3v3"
    allow_faulting: true
    allow_missing: true
  - name: "rssd07_12v"
    allow_faulting: true
    allow_missing: true
inputs:
  - name: "system/chassis/motherboard/rssd07"
    type: "dbus_presence"
    pullup: true
    signal_name: "RSSD07_PRESENT"
outputs:
  - name: "led_rssd07_power"
    type: "led"
    signal_name: "LED_RSSD07"
  - name: "RSSD07_RESET_N"
    type: "gpio"
    signal_name: "RSSD07_RESET"
    active_low: true
  - name: "RSSD07_PWRDIS"
    type: "gpio"
    signal_name: "RSSD07_POWER_EN"
    active_low: true
  - name: "RSSD07_SMBRST_N"
    type: "gpio"
    signal_name: "RSSD07_SMBRST"
    active_low: true
floating_signals:
  - "rssd07_3v3_Enabled"
  - "rssd07_12v_Enabled"
  - "rssd07_3v3_IsDummy"
  - "rssd07_12v_IsDummy"
  - "RSSD07_RESET_N_Enabled"

