---

# Controls power to the rulerdrives
power_sequencer:
  - DB1900Z_DEV0_Enable:
      in:
        or:
          - name: "RSSD01_PRESENT"
          - name: "RSSD02_PRESENT"
          - name: "RSSD03_PRESENT"
          - name: "RSSD04_PRESENT"
          - name: "RSSD05_PRESENT"
          - name: "RSSD06_PRESENT"
          - name: "RSSD07_PRESENT"
          - name: "RSSD08_PRESENT"
          - name: "RSSD09_PRESENT"
          - name: "RSSD10_PRESENT"
          - name: "RSSD11_PRESENT"
          - name: "RSSD12_PRESENT"
          - name: "RSSD13_PRESENT"
          - name: "RSSD14_PRESENT"
          - name: "RSSD15_PRESENT"
          - name: "RSSD16_PRESENT"
        and:
          - name: "FM_CK440Q_DEV_EN_Enabled"
        and_then_or: false
      out:
        name: "FM_SSD_CLK_DRVR0_EN"

  - DB1900Z_DEV1_Enable:
      in:
        or:
          - name: "RSSD17_PRESENT"
          - name: "RSSD18_PRESENT"
          - name: "RSSD19_PRESENT"
          - name: "RSSD20_PRESENT"
          - name: "RSSD21_PRESENT"
          - name: "RSSD22_PRESENT"
          - name: "RSSD23_PRESENT"
          - name: "RSSD24_PRESENT"
          - name: "RSSD25_PRESENT"
          - name: "RSSD26_PRESENT"
          - name: "RSSD27_PRESENT"
          - name: "RSSD28_PRESENT"
          - name: "RSSD29_PRESENT"
          - name: "RSSD30_PRESENT"
          - name: "RSSD31_PRESENT"
          - name: "RSSD32_PRESENT"
        and:
          - name: "FM_CK440Q_DEV_EN_Enabled"
        and_then_or: false
      out:
        name: "FM_SSD_CLK_DRVR1_EN"

outputs:
  - name: "FM_SSD_CLK_DRVR0_EN"
    type: "gpio"
    signal_name: "FM_SSD_CLK_DRVR0_EN"
  - name: "FM_SSD_CLK_DRVR1_EN"
    type: "gpio"
    signal_name: "FM_SSD_CLK_DRVR1_EN"
