---
inputs:
  - name: "FM_BIOS_POST_CMPLT_N"
    type: "gpio"
    signal_name: "FM_BIOS_POST_CMPLT"
    active_low: true
    description: "Indicates that the host is done with silicon init."
    gate_input: true
    gated_idle_low: true

power_sequencer:

  # Detect current ACPI state
  - ACPI_STATE_IS_G3_Unit:
      in:
        or:
          - name: "RSMRST"
      out:
        name: "ACPI_STATE_IS_G3"

  - ACPI_STATE_IS_S5_Unit:
      in:
        and:
          - name: "RSMRST"
            invert: true
          - name: "FM_SLPS4"
          - name: "FM_SLPS3"
      out:
        name: "ACPI_STATE_IS_S5"

  - ACPI_STATE_IS_S0_Unit:
      in:
        and:
          - name: "RSMRST"
            invert: true
          - name: "PCH_PWROK"
          - name: "CPU0_SYS_PWROK"
          - name: "CPU1_SYS_PWROK"
          - name: "CPU2_SYS_PWROK"
          - name: "CPU3_SYS_PWROK"
          - name: "PLTRST"
            invert: true
          - name: "FM_SLPS4"
            invert: true
          - name: "FM_SLPS3"
            invert: true
      out:
        name: "ACPI_STATE_IS_S0"

  - POST_DONE_Unit:
      in:
        and:
          - name: "ACPI_STATE_IS_S0"
          - name: "FM_BIOS_POST_CMPLT"
      out:
        name: "STATE_POST_DONE"

immutables:
  - signal_name: "ACPI_STATE_IS_S3"
    value: false

# Special wake events
wake:
  # As PWRBTN is not supported, S5->S0 will actually be S5->G3->S0
  - PWRBTN_N:
    type: "PWRBTN"
    supported: false



