---

# Contains logic to power sequence an Intel Xeon CPU.

inputs:
  # FIVR_FAULT is not read as THERMTRIP_N is driven as well.
  - name: "H_LVT3_CPLD2_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD2_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.

  - name: "FM_CPU2_SKTOCC_N"
    signal_name: "FM_CPU2_SKTOCC"
    type: "gpio"
    active_low: true
    description: "CPU2 socket is occupied."

  - name: "PWRGD_PVTT_NPQ_CPU2"
    signal_name: "PWRGD_PVTT_NPQ_CPU2"
    type: "gpio"
    description: "VTT NPQ is stable"

  - name: "PWRGD_PVTT_RST_CPU2"
    signal_name: "PWRGD_PVTT_RST_CPU2"
    type: "gpio"
    description: "VTT RST is stable"

outputs:
  - name: "H_LVT3_CPU2_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_PROCHOT"
    active_low: true
    open_drain: true
    description: "CPU2 is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU2_MEM_NPQ_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_MEM_NPQ_HOT"
    active_low: true
    open_drain: true
    description: "CPU2 memory is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU2_MEM_RST_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU2_MEM_RST_HOT"
    active_low: true
    open_drain: true
    description: "CPU2 memory is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
    description: "Tell CPU2 DRAM power good."

  - name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
    description: "Tell CPU2 DRAM power good."

  - name: "RST_LVC3_CPU2_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU2_RESET"
    active_low: true
    description: "CPU2 RESET_N"

  - name: "PWRGD_LVC3_CPU2_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU2_PWRGOOD"
    description: "Tell CPU2 power good."

immutables:
  - signal_name: "H_LVT3_CPU2_MEM_NPQ_HOT"
    value: false
  - signal_name: "H_LVT3_CPU2_MEM_RST_HOT"
    value: false
  - signal_name: "H_LVT3_CPU2_PROCHOT"
    value: false

power_sequencer:

  # Vpp must be equal or higher than Vdd at all times.
  - PVPP_NPQ_Unit:
      in:
        or:
          - name: "pvddq_npq_Enabled"
            input_stable_usec: 30000 # JEDEC recommendation
          - name: "pvddq_npq_Enabled"
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
        and_then_or: true
      out:
        name: "pvpp_npq_On"

  - PVDDQ_NPQ_ReqOn_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
          - name: "pvpp_npq_PowerGood"
            input_stable_usec: 100
      out:
        name: "pvddq_npq_ReqOn"
  
  # Ramp after DDR_VPP
  - PVDDQ_NPQ_Unit:
      in:
        or:
          - name: "pvddq_npq_ReqOn"
          - name: "CPU2_VR_Off"
            invert: true
      out:
        name: "pvddq_npq_On"

  # Vpp must be equal or higher than Vdd at all times.
  - PVPP_RST_Unit:
      in:
        or:
          - name: "pvddq_rst_Enabled"
            input_stable_usec: 30000 # JEDEC recommendation
          - name: "pvddq_rst_Enabled"
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
        and_then_or: true
      out:
        name: "pvpp_rst_On"

  - PVDDQ_RST_ReqOn_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "pvpp_rst_PowerGood"
            input_stable_usec: 100
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
      out:
        name: "pvddq_rst_ReqOn"

  # Ramp after DDR_VPP
  - PVDDQ_RST_Unit:
      in:
        or:
          - name: "pvddq_rst_ReqOn"
          - name: "CPU2_VR_Off"
            invert: true
      out:
        name: "pvddq_rst_On"

  - PWRGD_LVC3_CPU2_NPQ_DRAM_G_Unit:
      in:
        and:
          - name: "pvddq_npq_PowerGood"
          - name: "pvpp_npq_PowerGood"
          - name: "PWRGD_PVTT_NPQ_CPU2"
      out:
        name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"

  - PWRGD_LVC3_CPU2_RST_DRAM_G_Unit:
      in:
        and:
          - name: "pvddq_rst_PowerGood"
          - name: "pvpp_rst_PowerGood"
          - name: "PWRGD_PVTT_RST_CPU2"
      out:
        name: "PWRGD_LVC3_CPU2_RST_DRAM_G"

  - CPU2_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU2_NPQ_DRAM_G"
          - name: "PWRGD_LVC3_CPU2_RST_DRAM_G"
        or:
          - name: "FM_CPU2_SKTOCC"
            invert: true
        and_then_or: true
      out:
        name: "CPU2_DDR_PWRGD"

  # PVCCIO must ramp before PVCCIN and PVCCSA, must retain until after PVCCIN
  # and PVCCSA goes low
  # A fault on PVCCIO must shutdown PVCCIN and PVCCSA
  - PVCCIO_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "CPU2_DDR_PWRGD"
            input_stable_usec: 100
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
        or:
          - name: "PVCCIO_CPU2_DELAY"
        and_then_or: true
      out:
        name: "pvccio_cpu2_On"

  - PVCCIO_CPU2_Delay_Unit:
      in:
        or:
          - name: "pvccin_cpu2_On"
          - name: "pvccsa_cpu2_On"
      out:
        name: "PVCCIO_CPU2_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "pvccio_cpu2_PowerGood" # Shutdown within 500usec if VCCIO is at fault
            input_stable_usec: 100
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
      out:
        name: "pvccin_cpu2_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - PVCCSA_CPU2_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "pvccin_cpu2_PowerGood"
            input_stable_usec: 100
          - name: "pvccio_cpu2_PowerGood"
          - name: "FM_CPU2_SKTOCC"
          - name: "CPU2_VR_Fault_Shutdown"
            invert: true
      out:
        name: "pvccsa_cpu2_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - CPU2_VR_PWRGD_Unit:
      in:
        and:
          - name: "pvccio_cpu2_PowerGood"
          - name: "pvccin_cpu2_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "pvccin_cpu2_PowerGood"
          - name: "pvccsa_cpu2_PowerGood"
      out:
        name: "CPU2_VR_PWRGD"

  - PWRGD_LVC3_CPU2_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU2_DDR_PWRGD"
            # PDG: 2usec max from VR failure to SYS_PWROK low
          - name: "CPU2_VR_PWRGD" # fast path
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "PWRGD_LVC3_CPU2_PWRGOOD"

  - CPU2_SYS_PWROK_Unit:
      in:
        and:
          - name: "CPU2_VR_PWRGD"
          - name: "CPU2_DDR_PWRGD"
        or:
          - name: "FM_CPU2_SKTOCC"
            invert: true
        and_then_or: true
      out:
        name: "CPU2_SYS_PWROK"
  
  - CPU2_VR_Off_Unit:
      in:
        or:
          - name: "pvccio_cpu2_Enabled"
          - name: "pvccin_cpu2_Enabled"
          - name: "pvccsa_cpu2_Enabled"
      out:
        name: "CPU2_VR_Off"
        active_low: true

  - CPU2_DDR_Off_Unit:
      in:
        and:
          - name: "pvddq_npq_Enabled"
          - name: "pvpp_npq_Enabled"
          - name: "pvddq_rst_Enabled"
          - name: "pvpp_rst_Enabled"
      out:
        name: "CPU2_DDR_Off"
        active_low: true
  
  - CPU2_VR_Off_Unit:
      in:
        and:
          - name: "CPU2_DDR_Off"
          - name: "CPU2_VR_Off"
      out:
        name: "CPU2_Off"
    
  - CPU2_VR_Fault_Unit:
      in:
        or:
          - name: "pvddq_npq_Fault"
          - name: "pvpp_npq_Fault"
          - name: "pvddq_rst_Fault"
          - name: "pvpp_rst_Fault"
          - name: "pvccio_cpu2_Fault"
          - name: "pvccin_cpu2_Fault"
          - name: "pvccsa_cpu2_Fault"
          - name: "CPU2_THERMTRIP"
        and:
          - name: "FM_CPU2_SKTOCC"
      out:
        name: "CPU2_VR_Fault"

  - CPU2_VR_Fault_Keep_Unit:
      in:
        or:
          - name: "CPU2_VR_Fault"
          - name: "CPU2_VR_Fault_Shutdown"
        and:
          - name: "CPU2_Off"
            invert: true
      out:
        name: "CPU2_VR_Fault_Shutdown"

  # The following violates multi-processor RESET_N spec
  - RST_LVC3_CPU2_RESET_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "PWRGD_LVC3_CPU2_PWRGOOD"
            invert: true
      out:
        name: "RST_LVC3_CPU2_RESET"

  - CPU2_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD2_THERMTRIP"
          - name: "CPU2_VR_PWRGD" # PDG: Ignore THERMTRIP until power is good
            input_stable_usec: 1500
          - name: "CPU2_VR_PWRGD"
      out:
        name: "CPU2_THERMTRIP"

regulators:
  - name: "pvpp_npq"
  - name: "pvpp_rst"
  - name: "pvddq_npq"
  - name: "pvddq_rst"
  - name: "pvccsa_cpu2"
  - name: "pvccin_cpu2"
  - name: "pvccio_cpu2"
