---

# Contains logic to power sequence an Intel Xeon CPU.

inputs:
  # FIVR_FAULT is not read as THERMTRIP_N is driven as well.
  - name: "H_LVT3_CPLD3_THERMTRIP_N"
    signal_name: "H_LVT3_CPLD3_THERMTRIP"
    type: "gpio"
    active_low: true
    description: >
      THERMTRIP_N is set on over tempertature condition or internal FIVR fault.
    gate_input: true
    gated_idle_high: true

  - name: "system/chassis/motherboard/cpu3"
    type: "dbus_presence"
    pullup: true
    signal_name: "FM_CPU3_SKTOCC"
    description: "CPU3 socket is occupied."

  - name: "PWRGD_PVTT_UVW_CPU3"
    signal_name: "PWRGD_PVTT_UVW_CPU3"
    type: "gpio"
    description: "VTT UVW is stable"

  - name: "PWRGD_PVTT_XYZ_CPU3"
    signal_name: "PWRGD_PVTT_XYZ_CPU3"
    type: "gpio"
    description: "VTT XYZ is stable"

outputs:
  - name: "H_LVT3_CPU3_PROCHOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_PROCHOT"
    active_low: true
    open_drain: true
    description: "CPU3 is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU3_MEM_UVW_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_MEM_UVW_HOT"
    active_low: true
    open_drain: true
    description: "CPU3 memory is hot and throttling. Open Drain."

  - name: "H_LVT3_CPU3_MEM_XYZ_HOT_N"
    type: "gpio"
    signal_name: "H_LVT3_CPU3_MEM_XYZ_HOT"
    active_low: true
    open_drain: true
    description: "CPU3 memory is hot and throttling. Open Drain."

  - name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
    description: "Tell CPU3 DRAM power good."

  - name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
    description: "Tell CPU3 DRAM power good."

  - name: "RST_LVC3_CPU3_RESET_N"
    type: "gpio"
    signal_name: "RST_LVC3_CPU3_RESET"
    active_low: true
    description: "CPU3 RESET_N"

  - name: "PWRGD_LVC3_CPU3_PWRGOOD"
    type: "gpio"
    signal_name: "PWRGD_LVC3_CPU3_PWRGOOD"
    description: "Tell CPU3 power good."

immutables:
  - signal_name: "H_LVT3_CPU3_MEM_UVW_HOT"
    value: false
  - signal_name: "H_LVT3_CPU3_MEM_XYZ_HOT"
    value: false
  - signal_name: "H_LVT3_CPU3_PROCHOT"
    value: false

power_sequencer:

  # Vpp must be equal or higher than Vdd at all times.
  - PVPP_UVW_Unit:
      in:
        or:
          - name: "pvddq_uvw_Enabled"
            input_stable_usec: 30000 # JEDEC recommendation
          - name: "pvddq_uvw_Enabled"
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
        and_then_or: true
      out:
        name: "pvpp_uvw_On"

  - PVDDQ_UVW_ReqOn_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
          - name: "pvpp_uvw_PowerGood"
            input_stable_usec: 100
      out:
        name: "pvddq_uvw_ReqOn"
  
  # Ramp after DDR_VPP
  - PVDDQ_UVW_Unit:
      in:
        or:
          - name: "pvddq_uvw_ReqOn"
          - name: "CPU3_VR_Off"
            invert: true
      out:
        name: "pvddq_uvw_On"

  # Vpp must be equal or higher than Vdd at all times.
  - PVPP_XYZ_Unit:
      in:
        or:
          - name: "pvddq_xyz_Enabled"
            input_stable_usec: 30000 # JEDEC recommendation
          - name: "pvddq_xyz_Enabled"
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
        and_then_or: true
      out:
        name: "pvpp_xyz_On"

  - PVDDQ_XYZ_ReqOn_Unit:
      in:
        and:
          - name: "DDR_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "pvpp_xyz_PowerGood"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
      out:
        name: "pvddq_xyz_ReqOn"

  # Ramp after DDR_VPP
  - PVDDQ_XYZ_Unit:
      in:
        or:
          - name: "pvddq_xyz_ReqOn"
          - name: "CPU3_VR_Off"
            invert: true
      out:
        name: "pvddq_xyz_On"

  - PWRGD_LVC3_CPU3_UVW_DRAM_G_Unit:
      in:
        and:
          - name: "pvddq_uvw_PowerGood"
          - name: "pvpp_uvw_PowerGood"
          - name: "PWRGD_PVTT_UVW_CPU3"
      out:
        name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"

  - PWRGD_LVC3_CPU3_XYZ_DRAM_G_Unit:
      in:
        and:
          - name: "pvddq_xyz_PowerGood"
          - name: "pvpp_xyz_PowerGood"
          - name: "PWRGD_PVTT_XYZ_CPU3"
      out:
        name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"

  - CPU3_DDR_PWRGD_Unit:
      in:
        and:
          - name: "PWRGD_LVC3_CPU3_UVW_DRAM_G"
          - name: "PWRGD_LVC3_CPU3_XYZ_DRAM_G"
        or:
          - name: "FM_CPU3_SKTOCC"
            invert: true
        and_then_or: true
      out:
        name: "CPU3_DDR_PWRGD"

  # PVCCIO must ramp before PVCCIN and PVCCSA, must retain until after PVCCIN
  # and PVCCSA goes low
  # A fault on PVCCIO must shutdown PVCCIN and PVCCSA
  - PVCCIO_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU0_SYS_PWROK"
          - name: "CPU3_DDR_PWRGD"
            input_stable_usec: 100
          - name: "CPU3_DDR_PWRGD"
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
        or:
          - name: "PVCCIO_CPU3_DELAY"
        and_then_or: true
      out:
        name: "pvccio_cpu3_On"

  - PVCCIO_CPU3_Delay_Unit:
      in:
        or:
          - name: "pvccin_cpu3_On"
          - name: "pvccsa_cpu3_On"
      out:
        name: "PVCCIO_CPU3_DELAY"
      delay_usec: 5000

  - PVCCIN_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_DDR_PWRGD"
          - name: "CPU0_SYS_PWROK"
          - name: "pvccio_cpu3_PowerGood" # Wait for PVCCIO_CPU3_DELAY to not glitch
            input_stable_usec: 10000
          - name: "pvccio_cpu3_PowerGood" # Shutdown within 500usec if VCCIO is at fault
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
      out:
        name: "pvccin_cpu3_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - PVCCSA_CPU3_Unit:
      in:
        and:
          - name: "CPU_POWER"
          - name: "CPU3_DDR_PWRGD"
          - name: "CPU0_SYS_PWROK"
          - name: "pvccio_cpu3_PowerGood" # Wait for PVCCIO_CPU3_DELAY to not glitch
            input_stable_usec: 10000
          - name: "pvccio_cpu3_PowerGood"
          - name: "pvccin_cpu3_PowerGood"
            input_stable_usec: 100
          - name: "FM_CPU3_SKTOCC"
          - name: "CPU3_VR_Fault_Shutdown"
            invert: true
      out:
        name: "pvccsa_cpu3_On"
      delay_usec: 10 # Must retain for at least 10usec after shutdown

  - CPU3_VR_PWRGD_Unit:
      in:
        and:
          - name: "pvccio_cpu3_PowerGood"
          - name: "pvccin_cpu3_PowerGood"
            input_stable_usec: 1800  # CPUPWRGD must assert 1.8msec after PVCCIN
          - name: "pvccin_cpu3_PowerGood"
          - name: "pvccsa_cpu3_PowerGood"
      out:
        name: "CPU3_VR_PWRGD"

  - PWRGD_LVC3_CPU3_PWRGOOD_Unit:
      in:
        and:
          - name: "CPU3_DDR_PWRGD"
            # PDG: 2usec max from VR failure to SYS_PWROK low
          - name: "CPU3_VR_PWRGD" # fast path
          - name: "PWRGD_CPUPWRGD" # signal from PCH (slow)
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "PWRGD_LVC3_CPU3_PWRGOOD"

  - CPU3_SYS_PWROK_Unit:
      in:
        and:
          - name: "CPU3_VR_PWRGD"
          - name: "CPU3_DDR_PWRGD"
        or:
          - name: "FM_CPU3_SKTOCC"
            invert: true
        and_then_or: true
      out:
        name: "CPU3_SYS_PWROK"
  
  - CPU3_VR_Off_Unit:
      in:
        or:
          - name: "pvccio_cpu3_Enabled"
          - name: "pvccin_cpu3_Enabled"
          - name: "pvccsa_cpu3_Enabled"
      out:
        name: "CPU3_VR_Off"
        active_low: true

  - CPU3_DDR_Off_Unit:
      in:
        or:
          - name: "pvddq_uvw_Enabled"
          - name: "pvpp_uvw_Enabled"
          - name: "pvddq_xyz_Enabled"
          - name: "pvpp_xyz_Enabled"
          - name: "PWRGD_PVTT_UVW_CPU3"
          - name: "PWRGD_PVTT_XYZ_CPU3"
      out:
        name: "CPU3_DDR_Off"
        active_low: true
  
  - CPU3_VR_Off_Unit:
      in:
        and:
          - name: "CPU3_DDR_Off"
          - name: "CPU3_VR_Off"
      out:
        name: "CPU3_Off"
    
  - CPU3_VR_Fault_Unit:
      in:
        or:
          - name: "pvddq_uvw_Fault"
          - name: "pvpp_uvw_Fault"
          - name: "pvddq_xyz_Fault"
          - name: "pvpp_xyz_Fault"
          - name: "pvccio_cpu3_Fault"
          - name: "pvccin_cpu3_Fault"
          - name: "pvccsa_cpu3_Fault"
          - name: "CPU3_THERMTRIP"
        and:
          - name: "FM_CPU3_SKTOCC"
      out:
        name: "CPU3_VR_Fault"

  - CPU3_VR_Fault_Keep_Unit:
      in:
        or:
          - name: "CPU3_VR_Fault"
          - name: "CPU3_VR_Fault_Shutdown"
        and:
          - name: "CPU3_Off"
            invert: true
      out:
        name: "CPU3_VR_Fault_Shutdown"

  # The following violates multi-processor RESET_N spec
  - RST_LVC3_CPU3_RESET_Unit:
      in:
        or:
          - name: "PLTRST"
          - name: "PWRGD_LVC3_CPU3_PWRGOOD"
            invert: true
      out:
        name: "RST_LVC3_CPU3_RESET"

  - CPU3_THERMTRIP_Unit:
      in:
        and:
          - name: "H_LVT3_CPLD3_THERMTRIP"
          - name: "CPU3_VR_PWRGD" # PDG: Ignore THERMTRIP until power is good
            input_stable_usec: 1500
          - name: "CPU3_VR_PWRGD"
      out:
        name: "CPU3_THERMTRIP"

  - H_LVT3_CPLD3_THERMTRIP_N_Enable_Unit:
      in:
        and:
          - name: "pvccio_cpu0_On"
          - name: "pvccio_cpu0_PowerGood"
      out:
        name: "H_LVT3_CPLD3_THERMTRIP_N_On"

regulators:
  - name: "pvpp_uvw"
  - name: "pvpp_xyz"
  - name: "pvddq_uvw"
  - name: "pvddq_xyz"
  - name: "pvccsa_cpu3"
  - name: "pvccin_cpu3"
  - name: "pvccio_cpu3"
